
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Equipo: 'Equipo',
  Mantenimiento: 'Mantenimiento',
  Usuario: 'Usuario'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const EquipoScalarFieldEnum = {
  id: 'id',
  codigoInventario: 'codigoInventario',
  nombre: 'nombre',
  tipo: 'tipo',
  marca: 'marca',
  modelo: 'modelo',
  numeroSerie: 'numeroSerie',
  ubicacion: 'ubicacion',
  estado: 'estado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EquipoScalarFieldEnum = (typeof EquipoScalarFieldEnum)[keyof typeof EquipoScalarFieldEnum]


export const MantenimientoScalarFieldEnum = {
  id: 'id',
  descripcion: 'descripcion',
  tipo: 'tipo',
  estado: 'estado',
  diagnostico: 'diagnostico',
  tecnico: 'tecnico',
  fecha: 'fecha',
  equipoId: 'equipoId'
} as const

export type MantenimientoScalarFieldEnum = (typeof MantenimientoScalarFieldEnum)[keyof typeof MantenimientoScalarFieldEnum]


export const UsuarioScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  correo: 'correo',
  claveHash: 'claveHash',
  rol: 'rol',
  activo: 'activo',
  creadoEn: 'creadoEn'
} as const

export type UsuarioScalarFieldEnum = (typeof UsuarioScalarFieldEnum)[keyof typeof UsuarioScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const EquipoOrderByRelevanceFieldEnum = {
  codigoInventario: 'codigoInventario',
  nombre: 'nombre',
  tipo: 'tipo',
  marca: 'marca',
  modelo: 'modelo',
  numeroSerie: 'numeroSerie',
  ubicacion: 'ubicacion'
} as const

export type EquipoOrderByRelevanceFieldEnum = (typeof EquipoOrderByRelevanceFieldEnum)[keyof typeof EquipoOrderByRelevanceFieldEnum]


export const MantenimientoOrderByRelevanceFieldEnum = {
  descripcion: 'descripcion',
  tipo: 'tipo',
  estado: 'estado',
  diagnostico: 'diagnostico',
  tecnico: 'tecnico'
} as const

export type MantenimientoOrderByRelevanceFieldEnum = (typeof MantenimientoOrderByRelevanceFieldEnum)[keyof typeof MantenimientoOrderByRelevanceFieldEnum]


export const UsuarioOrderByRelevanceFieldEnum = {
  nombre: 'nombre',
  correo: 'correo',
  claveHash: 'claveHash'
} as const

export type UsuarioOrderByRelevanceFieldEnum = (typeof UsuarioOrderByRelevanceFieldEnum)[keyof typeof UsuarioOrderByRelevanceFieldEnum]

