
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Mantenimiento` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Mantenimiento
 * 
 */
export type MantenimientoModel = runtime.Types.Result.DefaultSelection<Prisma.$MantenimientoPayload>

export type AggregateMantenimiento = {
  _count: MantenimientoCountAggregateOutputType | null
  _avg: MantenimientoAvgAggregateOutputType | null
  _sum: MantenimientoSumAggregateOutputType | null
  _min: MantenimientoMinAggregateOutputType | null
  _max: MantenimientoMaxAggregateOutputType | null
}

export type MantenimientoAvgAggregateOutputType = {
  id: number | null
  equipoId: number | null
  ticketId: number | null
}

export type MantenimientoSumAggregateOutputType = {
  id: number | null
  equipoId: number | null
  ticketId: number | null
}

export type MantenimientoMinAggregateOutputType = {
  id: number | null
  descripcion: string | null
  tipo: string | null
  estado: string | null
  diagnostico: string | null
  tecnico: string | null
  fecha: Date | null
  equipoId: number | null
  ticketId: number | null
}

export type MantenimientoMaxAggregateOutputType = {
  id: number | null
  descripcion: string | null
  tipo: string | null
  estado: string | null
  diagnostico: string | null
  tecnico: string | null
  fecha: Date | null
  equipoId: number | null
  ticketId: number | null
}

export type MantenimientoCountAggregateOutputType = {
  id: number
  descripcion: number
  tipo: number
  estado: number
  diagnostico: number
  tecnico: number
  fecha: number
  equipoId: number
  ticketId: number
  _all: number
}


export type MantenimientoAvgAggregateInputType = {
  id?: true
  equipoId?: true
  ticketId?: true
}

export type MantenimientoSumAggregateInputType = {
  id?: true
  equipoId?: true
  ticketId?: true
}

export type MantenimientoMinAggregateInputType = {
  id?: true
  descripcion?: true
  tipo?: true
  estado?: true
  diagnostico?: true
  tecnico?: true
  fecha?: true
  equipoId?: true
  ticketId?: true
}

export type MantenimientoMaxAggregateInputType = {
  id?: true
  descripcion?: true
  tipo?: true
  estado?: true
  diagnostico?: true
  tecnico?: true
  fecha?: true
  equipoId?: true
  ticketId?: true
}

export type MantenimientoCountAggregateInputType = {
  id?: true
  descripcion?: true
  tipo?: true
  estado?: true
  diagnostico?: true
  tecnico?: true
  fecha?: true
  equipoId?: true
  ticketId?: true
  _all?: true
}

export type MantenimientoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mantenimiento to aggregate.
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mantenimientos to fetch.
   */
  orderBy?: Prisma.MantenimientoOrderByWithRelationInput | Prisma.MantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mantenimientos
  **/
  _count?: true | MantenimientoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MantenimientoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MantenimientoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MantenimientoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MantenimientoMaxAggregateInputType
}

export type GetMantenimientoAggregateType<T extends MantenimientoAggregateArgs> = {
      [P in keyof T & keyof AggregateMantenimiento]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMantenimiento[P]>
    : Prisma.GetScalarType<T[P], AggregateMantenimiento[P]>
}




export type MantenimientoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MantenimientoWhereInput
  orderBy?: Prisma.MantenimientoOrderByWithAggregationInput | Prisma.MantenimientoOrderByWithAggregationInput[]
  by: Prisma.MantenimientoScalarFieldEnum[] | Prisma.MantenimientoScalarFieldEnum
  having?: Prisma.MantenimientoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MantenimientoCountAggregateInputType | true
  _avg?: MantenimientoAvgAggregateInputType
  _sum?: MantenimientoSumAggregateInputType
  _min?: MantenimientoMinAggregateInputType
  _max?: MantenimientoMaxAggregateInputType
}

export type MantenimientoGroupByOutputType = {
  id: number
  descripcion: string
  tipo: string
  estado: string
  diagnostico: string | null
  tecnico: string | null
  fecha: Date
  equipoId: number
  ticketId: number | null
  _count: MantenimientoCountAggregateOutputType | null
  _avg: MantenimientoAvgAggregateOutputType | null
  _sum: MantenimientoSumAggregateOutputType | null
  _min: MantenimientoMinAggregateOutputType | null
  _max: MantenimientoMaxAggregateOutputType | null
}

export type GetMantenimientoGroupByPayload<T extends MantenimientoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MantenimientoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MantenimientoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MantenimientoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MantenimientoGroupByOutputType[P]>
      }
    >
  >



export type MantenimientoWhereInput = {
  AND?: Prisma.MantenimientoWhereInput | Prisma.MantenimientoWhereInput[]
  OR?: Prisma.MantenimientoWhereInput[]
  NOT?: Prisma.MantenimientoWhereInput | Prisma.MantenimientoWhereInput[]
  id?: Prisma.IntFilter<"Mantenimiento"> | number
  descripcion?: Prisma.StringFilter<"Mantenimiento"> | string
  tipo?: Prisma.StringFilter<"Mantenimiento"> | string
  estado?: Prisma.StringFilter<"Mantenimiento"> | string
  diagnostico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  tecnico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  fecha?: Prisma.DateTimeFilter<"Mantenimiento"> | Date | string
  equipoId?: Prisma.IntFilter<"Mantenimiento"> | number
  ticketId?: Prisma.IntNullableFilter<"Mantenimiento"> | number | null
  equipo?: Prisma.XOR<Prisma.EquipoScalarRelationFilter, Prisma.EquipoWhereInput>
  ticket?: Prisma.XOR<Prisma.TicketsNullableScalarRelationFilter, Prisma.ticketsWhereInput> | null
  repuestos?: Prisma.RepuestoMantenimientoListRelationFilter
}

export type MantenimientoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrderInput | Prisma.SortOrder
  tecnico?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrderInput | Prisma.SortOrder
  equipo?: Prisma.EquipoOrderByWithRelationInput
  ticket?: Prisma.ticketsOrderByWithRelationInput
  repuestos?: Prisma.RepuestoMantenimientoOrderByRelationAggregateInput
  _relevance?: Prisma.MantenimientoOrderByRelevanceInput
}

export type MantenimientoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MantenimientoWhereInput | Prisma.MantenimientoWhereInput[]
  OR?: Prisma.MantenimientoWhereInput[]
  NOT?: Prisma.MantenimientoWhereInput | Prisma.MantenimientoWhereInput[]
  descripcion?: Prisma.StringFilter<"Mantenimiento"> | string
  tipo?: Prisma.StringFilter<"Mantenimiento"> | string
  estado?: Prisma.StringFilter<"Mantenimiento"> | string
  diagnostico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  tecnico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  fecha?: Prisma.DateTimeFilter<"Mantenimiento"> | Date | string
  equipoId?: Prisma.IntFilter<"Mantenimiento"> | number
  ticketId?: Prisma.IntNullableFilter<"Mantenimiento"> | number | null
  equipo?: Prisma.XOR<Prisma.EquipoScalarRelationFilter, Prisma.EquipoWhereInput>
  ticket?: Prisma.XOR<Prisma.TicketsNullableScalarRelationFilter, Prisma.ticketsWhereInput> | null
  repuestos?: Prisma.RepuestoMantenimientoListRelationFilter
}, "id">

export type MantenimientoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrderInput | Prisma.SortOrder
  tecnico?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MantenimientoCountOrderByAggregateInput
  _avg?: Prisma.MantenimientoAvgOrderByAggregateInput
  _max?: Prisma.MantenimientoMaxOrderByAggregateInput
  _min?: Prisma.MantenimientoMinOrderByAggregateInput
  _sum?: Prisma.MantenimientoSumOrderByAggregateInput
}

export type MantenimientoScalarWhereWithAggregatesInput = {
  AND?: Prisma.MantenimientoScalarWhereWithAggregatesInput | Prisma.MantenimientoScalarWhereWithAggregatesInput[]
  OR?: Prisma.MantenimientoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MantenimientoScalarWhereWithAggregatesInput | Prisma.MantenimientoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Mantenimiento"> | number
  descripcion?: Prisma.StringWithAggregatesFilter<"Mantenimiento"> | string
  tipo?: Prisma.StringWithAggregatesFilter<"Mantenimiento"> | string
  estado?: Prisma.StringWithAggregatesFilter<"Mantenimiento"> | string
  diagnostico?: Prisma.StringNullableWithAggregatesFilter<"Mantenimiento"> | string | null
  tecnico?: Prisma.StringNullableWithAggregatesFilter<"Mantenimiento"> | string | null
  fecha?: Prisma.DateTimeWithAggregatesFilter<"Mantenimiento"> | Date | string
  equipoId?: Prisma.IntWithAggregatesFilter<"Mantenimiento"> | number
  ticketId?: Prisma.IntNullableWithAggregatesFilter<"Mantenimiento"> | number | null
}

export type MantenimientoCreateInput = {
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipo: Prisma.EquipoCreateNestedOneWithoutMantenimientosInput
  ticket?: Prisma.ticketsCreateNestedOneWithoutMantenimientosInput
  repuestos?: Prisma.RepuestoMantenimientoCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoUncheckedCreateInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipoId: number
  ticketId?: number | null
  repuestos?: Prisma.RepuestoMantenimientoUncheckedCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoUpdateInput = {
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipo?: Prisma.EquipoUpdateOneRequiredWithoutMantenimientosNestedInput
  ticket?: Prisma.ticketsUpdateOneWithoutMantenimientosNestedInput
  repuestos?: Prisma.RepuestoMantenimientoUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipoId?: Prisma.IntFieldUpdateOperationsInput | number
  ticketId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  repuestos?: Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoCreateManyInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipoId: number
  ticketId?: number | null
}

export type MantenimientoUpdateManyMutationInput = {
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipoId?: Prisma.IntFieldUpdateOperationsInput | number
  ticketId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MantenimientoListRelationFilter = {
  every?: Prisma.MantenimientoWhereInput
  some?: Prisma.MantenimientoWhereInput
  none?: Prisma.MantenimientoWhereInput
}

export type MantenimientoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MantenimientoOrderByRelevanceInput = {
  fields: Prisma.MantenimientoOrderByRelevanceFieldEnum | Prisma.MantenimientoOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type MantenimientoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tecnico?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type MantenimientoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type MantenimientoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tecnico?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type MantenimientoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  diagnostico?: Prisma.SortOrder
  tecnico?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type MantenimientoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  equipoId?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
}

export type MantenimientoScalarRelationFilter = {
  is?: Prisma.MantenimientoWhereInput
  isNot?: Prisma.MantenimientoWhereInput
}

export type MantenimientoCreateNestedManyWithoutEquipoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput> | Prisma.MantenimientoCreateWithoutEquipoInput[] | Prisma.MantenimientoUncheckedCreateWithoutEquipoInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutEquipoInput | Prisma.MantenimientoCreateOrConnectWithoutEquipoInput[]
  createMany?: Prisma.MantenimientoCreateManyEquipoInputEnvelope
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
}

export type MantenimientoUncheckedCreateNestedManyWithoutEquipoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput> | Prisma.MantenimientoCreateWithoutEquipoInput[] | Prisma.MantenimientoUncheckedCreateWithoutEquipoInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutEquipoInput | Prisma.MantenimientoCreateOrConnectWithoutEquipoInput[]
  createMany?: Prisma.MantenimientoCreateManyEquipoInputEnvelope
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
}

export type MantenimientoUpdateManyWithoutEquipoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput> | Prisma.MantenimientoCreateWithoutEquipoInput[] | Prisma.MantenimientoUncheckedCreateWithoutEquipoInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutEquipoInput | Prisma.MantenimientoCreateOrConnectWithoutEquipoInput[]
  upsert?: Prisma.MantenimientoUpsertWithWhereUniqueWithoutEquipoInput | Prisma.MantenimientoUpsertWithWhereUniqueWithoutEquipoInput[]
  createMany?: Prisma.MantenimientoCreateManyEquipoInputEnvelope
  set?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  delete?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  update?: Prisma.MantenimientoUpdateWithWhereUniqueWithoutEquipoInput | Prisma.MantenimientoUpdateWithWhereUniqueWithoutEquipoInput[]
  updateMany?: Prisma.MantenimientoUpdateManyWithWhereWithoutEquipoInput | Prisma.MantenimientoUpdateManyWithWhereWithoutEquipoInput[]
  deleteMany?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
}

export type MantenimientoUncheckedUpdateManyWithoutEquipoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput> | Prisma.MantenimientoCreateWithoutEquipoInput[] | Prisma.MantenimientoUncheckedCreateWithoutEquipoInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutEquipoInput | Prisma.MantenimientoCreateOrConnectWithoutEquipoInput[]
  upsert?: Prisma.MantenimientoUpsertWithWhereUniqueWithoutEquipoInput | Prisma.MantenimientoUpsertWithWhereUniqueWithoutEquipoInput[]
  createMany?: Prisma.MantenimientoCreateManyEquipoInputEnvelope
  set?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  delete?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  update?: Prisma.MantenimientoUpdateWithWhereUniqueWithoutEquipoInput | Prisma.MantenimientoUpdateWithWhereUniqueWithoutEquipoInput[]
  updateMany?: Prisma.MantenimientoUpdateManyWithWhereWithoutEquipoInput | Prisma.MantenimientoUpdateManyWithWhereWithoutEquipoInput[]
  deleteMany?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type MantenimientoCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput> | Prisma.MantenimientoCreateWithoutTicketInput[] | Prisma.MantenimientoUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutTicketInput | Prisma.MantenimientoCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.MantenimientoCreateManyTicketInputEnvelope
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
}

export type MantenimientoUncheckedCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput> | Prisma.MantenimientoCreateWithoutTicketInput[] | Prisma.MantenimientoUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutTicketInput | Prisma.MantenimientoCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.MantenimientoCreateManyTicketInputEnvelope
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
}

export type MantenimientoUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput> | Prisma.MantenimientoCreateWithoutTicketInput[] | Prisma.MantenimientoUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutTicketInput | Prisma.MantenimientoCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.MantenimientoUpsertWithWhereUniqueWithoutTicketInput | Prisma.MantenimientoUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.MantenimientoCreateManyTicketInputEnvelope
  set?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  delete?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  update?: Prisma.MantenimientoUpdateWithWhereUniqueWithoutTicketInput | Prisma.MantenimientoUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.MantenimientoUpdateManyWithWhereWithoutTicketInput | Prisma.MantenimientoUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
}

export type MantenimientoUncheckedUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput> | Prisma.MantenimientoCreateWithoutTicketInput[] | Prisma.MantenimientoUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutTicketInput | Prisma.MantenimientoCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.MantenimientoUpsertWithWhereUniqueWithoutTicketInput | Prisma.MantenimientoUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.MantenimientoCreateManyTicketInputEnvelope
  set?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  delete?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  connect?: Prisma.MantenimientoWhereUniqueInput | Prisma.MantenimientoWhereUniqueInput[]
  update?: Prisma.MantenimientoUpdateWithWhereUniqueWithoutTicketInput | Prisma.MantenimientoUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.MantenimientoUpdateManyWithWhereWithoutTicketInput | Prisma.MantenimientoUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
}

export type MantenimientoCreateNestedOneWithoutRepuestosInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutRepuestosInput, Prisma.MantenimientoUncheckedCreateWithoutRepuestosInput>
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutRepuestosInput
  connect?: Prisma.MantenimientoWhereUniqueInput
}

export type MantenimientoUpdateOneRequiredWithoutRepuestosNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoCreateWithoutRepuestosInput, Prisma.MantenimientoUncheckedCreateWithoutRepuestosInput>
  connectOrCreate?: Prisma.MantenimientoCreateOrConnectWithoutRepuestosInput
  upsert?: Prisma.MantenimientoUpsertWithoutRepuestosInput
  connect?: Prisma.MantenimientoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MantenimientoUpdateToOneWithWhereWithoutRepuestosInput, Prisma.MantenimientoUpdateWithoutRepuestosInput>, Prisma.MantenimientoUncheckedUpdateWithoutRepuestosInput>
}

export type MantenimientoCreateWithoutEquipoInput = {
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  ticket?: Prisma.ticketsCreateNestedOneWithoutMantenimientosInput
  repuestos?: Prisma.RepuestoMantenimientoCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoUncheckedCreateWithoutEquipoInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  ticketId?: number | null
  repuestos?: Prisma.RepuestoMantenimientoUncheckedCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoCreateOrConnectWithoutEquipoInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput>
}

export type MantenimientoCreateManyEquipoInputEnvelope = {
  data: Prisma.MantenimientoCreateManyEquipoInput | Prisma.MantenimientoCreateManyEquipoInput[]
  skipDuplicates?: boolean
}

export type MantenimientoUpsertWithWhereUniqueWithoutEquipoInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  update: Prisma.XOR<Prisma.MantenimientoUpdateWithoutEquipoInput, Prisma.MantenimientoUncheckedUpdateWithoutEquipoInput>
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutEquipoInput, Prisma.MantenimientoUncheckedCreateWithoutEquipoInput>
}

export type MantenimientoUpdateWithWhereUniqueWithoutEquipoInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  data: Prisma.XOR<Prisma.MantenimientoUpdateWithoutEquipoInput, Prisma.MantenimientoUncheckedUpdateWithoutEquipoInput>
}

export type MantenimientoUpdateManyWithWhereWithoutEquipoInput = {
  where: Prisma.MantenimientoScalarWhereInput
  data: Prisma.XOR<Prisma.MantenimientoUpdateManyMutationInput, Prisma.MantenimientoUncheckedUpdateManyWithoutEquipoInput>
}

export type MantenimientoScalarWhereInput = {
  AND?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
  OR?: Prisma.MantenimientoScalarWhereInput[]
  NOT?: Prisma.MantenimientoScalarWhereInput | Prisma.MantenimientoScalarWhereInput[]
  id?: Prisma.IntFilter<"Mantenimiento"> | number
  descripcion?: Prisma.StringFilter<"Mantenimiento"> | string
  tipo?: Prisma.StringFilter<"Mantenimiento"> | string
  estado?: Prisma.StringFilter<"Mantenimiento"> | string
  diagnostico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  tecnico?: Prisma.StringNullableFilter<"Mantenimiento"> | string | null
  fecha?: Prisma.DateTimeFilter<"Mantenimiento"> | Date | string
  equipoId?: Prisma.IntFilter<"Mantenimiento"> | number
  ticketId?: Prisma.IntNullableFilter<"Mantenimiento"> | number | null
}

export type MantenimientoCreateWithoutTicketInput = {
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipo: Prisma.EquipoCreateNestedOneWithoutMantenimientosInput
  repuestos?: Prisma.RepuestoMantenimientoCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoUncheckedCreateWithoutTicketInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipoId: number
  repuestos?: Prisma.RepuestoMantenimientoUncheckedCreateNestedManyWithoutMantenimientoInput
}

export type MantenimientoCreateOrConnectWithoutTicketInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput>
}

export type MantenimientoCreateManyTicketInputEnvelope = {
  data: Prisma.MantenimientoCreateManyTicketInput | Prisma.MantenimientoCreateManyTicketInput[]
  skipDuplicates?: boolean
}

export type MantenimientoUpsertWithWhereUniqueWithoutTicketInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  update: Prisma.XOR<Prisma.MantenimientoUpdateWithoutTicketInput, Prisma.MantenimientoUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutTicketInput, Prisma.MantenimientoUncheckedCreateWithoutTicketInput>
}

export type MantenimientoUpdateWithWhereUniqueWithoutTicketInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  data: Prisma.XOR<Prisma.MantenimientoUpdateWithoutTicketInput, Prisma.MantenimientoUncheckedUpdateWithoutTicketInput>
}

export type MantenimientoUpdateManyWithWhereWithoutTicketInput = {
  where: Prisma.MantenimientoScalarWhereInput
  data: Prisma.XOR<Prisma.MantenimientoUpdateManyMutationInput, Prisma.MantenimientoUncheckedUpdateManyWithoutTicketInput>
}

export type MantenimientoCreateWithoutRepuestosInput = {
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipo: Prisma.EquipoCreateNestedOneWithoutMantenimientosInput
  ticket?: Prisma.ticketsCreateNestedOneWithoutMantenimientosInput
}

export type MantenimientoUncheckedCreateWithoutRepuestosInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipoId: number
  ticketId?: number | null
}

export type MantenimientoCreateOrConnectWithoutRepuestosInput = {
  where: Prisma.MantenimientoWhereUniqueInput
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutRepuestosInput, Prisma.MantenimientoUncheckedCreateWithoutRepuestosInput>
}

export type MantenimientoUpsertWithoutRepuestosInput = {
  update: Prisma.XOR<Prisma.MantenimientoUpdateWithoutRepuestosInput, Prisma.MantenimientoUncheckedUpdateWithoutRepuestosInput>
  create: Prisma.XOR<Prisma.MantenimientoCreateWithoutRepuestosInput, Prisma.MantenimientoUncheckedCreateWithoutRepuestosInput>
  where?: Prisma.MantenimientoWhereInput
}

export type MantenimientoUpdateToOneWithWhereWithoutRepuestosInput = {
  where?: Prisma.MantenimientoWhereInput
  data: Prisma.XOR<Prisma.MantenimientoUpdateWithoutRepuestosInput, Prisma.MantenimientoUncheckedUpdateWithoutRepuestosInput>
}

export type MantenimientoUpdateWithoutRepuestosInput = {
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipo?: Prisma.EquipoUpdateOneRequiredWithoutMantenimientosNestedInput
  ticket?: Prisma.ticketsUpdateOneWithoutMantenimientosNestedInput
}

export type MantenimientoUncheckedUpdateWithoutRepuestosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipoId?: Prisma.IntFieldUpdateOperationsInput | number
  ticketId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MantenimientoCreateManyEquipoInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  ticketId?: number | null
}

export type MantenimientoUpdateWithoutEquipoInput = {
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticket?: Prisma.ticketsUpdateOneWithoutMantenimientosNestedInput
  repuestos?: Prisma.RepuestoMantenimientoUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoUncheckedUpdateWithoutEquipoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  repuestos?: Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoUncheckedUpdateManyWithoutEquipoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MantenimientoCreateManyTicketInput = {
  id?: number
  descripcion: string
  tipo?: string
  estado?: string
  diagnostico?: string | null
  tecnico?: string | null
  fecha?: Date | string
  equipoId: number
}

export type MantenimientoUpdateWithoutTicketInput = {
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipo?: Prisma.EquipoUpdateOneRequiredWithoutMantenimientosNestedInput
  repuestos?: Prisma.RepuestoMantenimientoUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoUncheckedUpdateWithoutTicketInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipoId?: Prisma.IntFieldUpdateOperationsInput | number
  repuestos?: Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoNestedInput
}

export type MantenimientoUncheckedUpdateManyWithoutTicketInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  diagnostico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tecnico?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipoId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type MantenimientoCountOutputType
 */

export type MantenimientoCountOutputType = {
  repuestos: number
}

export type MantenimientoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  repuestos?: boolean | MantenimientoCountOutputTypeCountRepuestosArgs
}

/**
 * MantenimientoCountOutputType without action
 */
export type MantenimientoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoCountOutputType
   */
  select?: Prisma.MantenimientoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MantenimientoCountOutputType without action
 */
export type MantenimientoCountOutputTypeCountRepuestosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RepuestoMantenimientoWhereInput
}


export type MantenimientoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  descripcion?: boolean
  tipo?: boolean
  estado?: boolean
  diagnostico?: boolean
  tecnico?: boolean
  fecha?: boolean
  equipoId?: boolean
  ticketId?: boolean
  equipo?: boolean | Prisma.EquipoDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.Mantenimiento$ticketArgs<ExtArgs>
  repuestos?: boolean | Prisma.Mantenimiento$repuestosArgs<ExtArgs>
  _count?: boolean | Prisma.MantenimientoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mantenimiento"]>



export type MantenimientoSelectScalar = {
  id?: boolean
  descripcion?: boolean
  tipo?: boolean
  estado?: boolean
  diagnostico?: boolean
  tecnico?: boolean
  fecha?: boolean
  equipoId?: boolean
  ticketId?: boolean
}

export type MantenimientoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "descripcion" | "tipo" | "estado" | "diagnostico" | "tecnico" | "fecha" | "equipoId" | "ticketId", ExtArgs["result"]["mantenimiento"]>
export type MantenimientoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  equipo?: boolean | Prisma.EquipoDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.Mantenimiento$ticketArgs<ExtArgs>
  repuestos?: boolean | Prisma.Mantenimiento$repuestosArgs<ExtArgs>
  _count?: boolean | Prisma.MantenimientoCountOutputTypeDefaultArgs<ExtArgs>
}

export type $MantenimientoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mantenimiento"
  objects: {
    equipo: Prisma.$EquipoPayload<ExtArgs>
    ticket: Prisma.$ticketsPayload<ExtArgs> | null
    repuestos: Prisma.$RepuestoMantenimientoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    descripcion: string
    tipo: string
    estado: string
    diagnostico: string | null
    tecnico: string | null
    fecha: Date
    equipoId: number
    ticketId: number | null
  }, ExtArgs["result"]["mantenimiento"]>
  composites: {}
}

export type MantenimientoGetPayload<S extends boolean | null | undefined | MantenimientoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload, S>

export type MantenimientoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MantenimientoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MantenimientoCountAggregateInputType | true
  }

export interface MantenimientoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mantenimiento'], meta: { name: 'Mantenimiento' } }
  /**
   * Find zero or one Mantenimiento that matches the filter.
   * @param {MantenimientoFindUniqueArgs} args - Arguments to find a Mantenimiento
   * @example
   * // Get one Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MantenimientoFindUniqueArgs>(args: Prisma.SelectSubset<T, MantenimientoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mantenimiento that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MantenimientoFindUniqueOrThrowArgs} args - Arguments to find a Mantenimiento
   * @example
   * // Get one Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MantenimientoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MantenimientoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mantenimiento that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoFindFirstArgs} args - Arguments to find a Mantenimiento
   * @example
   * // Get one Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MantenimientoFindFirstArgs>(args?: Prisma.SelectSubset<T, MantenimientoFindFirstArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mantenimiento that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoFindFirstOrThrowArgs} args - Arguments to find a Mantenimiento
   * @example
   * // Get one Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MantenimientoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MantenimientoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mantenimientos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mantenimientos
   * const mantenimientos = await prisma.mantenimiento.findMany()
   * 
   * // Get first 10 Mantenimientos
   * const mantenimientos = await prisma.mantenimiento.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mantenimientoWithIdOnly = await prisma.mantenimiento.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MantenimientoFindManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mantenimiento.
   * @param {MantenimientoCreateArgs} args - Arguments to create a Mantenimiento.
   * @example
   * // Create one Mantenimiento
   * const Mantenimiento = await prisma.mantenimiento.create({
   *   data: {
   *     // ... data to create a Mantenimiento
   *   }
   * })
   * 
   */
  create<T extends MantenimientoCreateArgs>(args: Prisma.SelectSubset<T, MantenimientoCreateArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mantenimientos.
   * @param {MantenimientoCreateManyArgs} args - Arguments to create many Mantenimientos.
   * @example
   * // Create many Mantenimientos
   * const mantenimiento = await prisma.mantenimiento.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MantenimientoCreateManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Mantenimiento.
   * @param {MantenimientoDeleteArgs} args - Arguments to delete one Mantenimiento.
   * @example
   * // Delete one Mantenimiento
   * const Mantenimiento = await prisma.mantenimiento.delete({
   *   where: {
   *     // ... filter to delete one Mantenimiento
   *   }
   * })
   * 
   */
  delete<T extends MantenimientoDeleteArgs>(args: Prisma.SelectSubset<T, MantenimientoDeleteArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mantenimiento.
   * @param {MantenimientoUpdateArgs} args - Arguments to update one Mantenimiento.
   * @example
   * // Update one Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MantenimientoUpdateArgs>(args: Prisma.SelectSubset<T, MantenimientoUpdateArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mantenimientos.
   * @param {MantenimientoDeleteManyArgs} args - Arguments to filter Mantenimientos to delete.
   * @example
   * // Delete a few Mantenimientos
   * const { count } = await prisma.mantenimiento.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MantenimientoDeleteManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mantenimientos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mantenimientos
   * const mantenimiento = await prisma.mantenimiento.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MantenimientoUpdateManyArgs>(args: Prisma.SelectSubset<T, MantenimientoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Mantenimiento.
   * @param {MantenimientoUpsertArgs} args - Arguments to update or create a Mantenimiento.
   * @example
   * // Update or create a Mantenimiento
   * const mantenimiento = await prisma.mantenimiento.upsert({
   *   create: {
   *     // ... data to create a Mantenimiento
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mantenimiento we want to update
   *   }
   * })
   */
  upsert<T extends MantenimientoUpsertArgs>(args: Prisma.SelectSubset<T, MantenimientoUpsertArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mantenimientos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoCountArgs} args - Arguments to filter Mantenimientos to count.
   * @example
   * // Count the number of Mantenimientos
   * const count = await prisma.mantenimiento.count({
   *   where: {
   *     // ... the filter for the Mantenimientos we want to count
   *   }
   * })
  **/
  count<T extends MantenimientoCountArgs>(
    args?: Prisma.Subset<T, MantenimientoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MantenimientoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mantenimiento.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MantenimientoAggregateArgs>(args: Prisma.Subset<T, MantenimientoAggregateArgs>): Prisma.PrismaPromise<GetMantenimientoAggregateType<T>>

  /**
   * Group by Mantenimiento.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MantenimientoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MantenimientoGroupByArgs['orderBy'] }
      : { orderBy?: MantenimientoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MantenimientoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMantenimientoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mantenimiento model
 */
readonly fields: MantenimientoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mantenimiento.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MantenimientoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  equipo<T extends Prisma.EquipoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EquipoDefaultArgs<ExtArgs>>): Prisma.Prisma__EquipoClient<runtime.Types.Result.GetResult<Prisma.$EquipoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  ticket<T extends Prisma.Mantenimiento$ticketArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mantenimiento$ticketArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  repuestos<T extends Prisma.Mantenimiento$repuestosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mantenimiento$repuestosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mantenimiento model
 */
export interface MantenimientoFieldRefs {
  readonly id: Prisma.FieldRef<"Mantenimiento", 'Int'>
  readonly descripcion: Prisma.FieldRef<"Mantenimiento", 'String'>
  readonly tipo: Prisma.FieldRef<"Mantenimiento", 'String'>
  readonly estado: Prisma.FieldRef<"Mantenimiento", 'String'>
  readonly diagnostico: Prisma.FieldRef<"Mantenimiento", 'String'>
  readonly tecnico: Prisma.FieldRef<"Mantenimiento", 'String'>
  readonly fecha: Prisma.FieldRef<"Mantenimiento", 'DateTime'>
  readonly equipoId: Prisma.FieldRef<"Mantenimiento", 'Int'>
  readonly ticketId: Prisma.FieldRef<"Mantenimiento", 'Int'>
}
    

// Custom InputTypes
/**
 * Mantenimiento findUnique
 */
export type MantenimientoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which Mantenimiento to fetch.
   */
  where: Prisma.MantenimientoWhereUniqueInput
}

/**
 * Mantenimiento findUniqueOrThrow
 */
export type MantenimientoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which Mantenimiento to fetch.
   */
  where: Prisma.MantenimientoWhereUniqueInput
}

/**
 * Mantenimiento findFirst
 */
export type MantenimientoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which Mantenimiento to fetch.
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mantenimientos to fetch.
   */
  orderBy?: Prisma.MantenimientoOrderByWithRelationInput | Prisma.MantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mantenimientos.
   */
  cursor?: Prisma.MantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mantenimientos.
   */
  distinct?: Prisma.MantenimientoScalarFieldEnum | Prisma.MantenimientoScalarFieldEnum[]
}

/**
 * Mantenimiento findFirstOrThrow
 */
export type MantenimientoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which Mantenimiento to fetch.
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mantenimientos to fetch.
   */
  orderBy?: Prisma.MantenimientoOrderByWithRelationInput | Prisma.MantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mantenimientos.
   */
  cursor?: Prisma.MantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mantenimientos.
   */
  distinct?: Prisma.MantenimientoScalarFieldEnum | Prisma.MantenimientoScalarFieldEnum[]
}

/**
 * Mantenimiento findMany
 */
export type MantenimientoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which Mantenimientos to fetch.
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mantenimientos to fetch.
   */
  orderBy?: Prisma.MantenimientoOrderByWithRelationInput | Prisma.MantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mantenimientos.
   */
  cursor?: Prisma.MantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mantenimientos.
   */
  distinct?: Prisma.MantenimientoScalarFieldEnum | Prisma.MantenimientoScalarFieldEnum[]
}

/**
 * Mantenimiento create
 */
export type MantenimientoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * The data needed to create a Mantenimiento.
   */
  data: Prisma.XOR<Prisma.MantenimientoCreateInput, Prisma.MantenimientoUncheckedCreateInput>
}

/**
 * Mantenimiento createMany
 */
export type MantenimientoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mantenimientos.
   */
  data: Prisma.MantenimientoCreateManyInput | Prisma.MantenimientoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mantenimiento update
 */
export type MantenimientoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * The data needed to update a Mantenimiento.
   */
  data: Prisma.XOR<Prisma.MantenimientoUpdateInput, Prisma.MantenimientoUncheckedUpdateInput>
  /**
   * Choose, which Mantenimiento to update.
   */
  where: Prisma.MantenimientoWhereUniqueInput
}

/**
 * Mantenimiento updateMany
 */
export type MantenimientoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mantenimientos.
   */
  data: Prisma.XOR<Prisma.MantenimientoUpdateManyMutationInput, Prisma.MantenimientoUncheckedUpdateManyInput>
  /**
   * Filter which Mantenimientos to update
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * Limit how many Mantenimientos to update.
   */
  limit?: number
}

/**
 * Mantenimiento upsert
 */
export type MantenimientoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * The filter to search for the Mantenimiento to update in case it exists.
   */
  where: Prisma.MantenimientoWhereUniqueInput
  /**
   * In case the Mantenimiento found by the `where` argument doesn't exist, create a new Mantenimiento with this data.
   */
  create: Prisma.XOR<Prisma.MantenimientoCreateInput, Prisma.MantenimientoUncheckedCreateInput>
  /**
   * In case the Mantenimiento was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MantenimientoUpdateInput, Prisma.MantenimientoUncheckedUpdateInput>
}

/**
 * Mantenimiento delete
 */
export type MantenimientoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  /**
   * Filter which Mantenimiento to delete.
   */
  where: Prisma.MantenimientoWhereUniqueInput
}

/**
 * Mantenimiento deleteMany
 */
export type MantenimientoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mantenimientos to delete
   */
  where?: Prisma.MantenimientoWhereInput
  /**
   * Limit how many Mantenimientos to delete.
   */
  limit?: number
}

/**
 * Mantenimiento.ticket
 */
export type Mantenimiento$ticketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  where?: Prisma.ticketsWhereInput
}

/**
 * Mantenimiento.repuestos
 */
export type Mantenimiento$repuestosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  where?: Prisma.RepuestoMantenimientoWhereInput
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RepuestoMantenimientoScalarFieldEnum | Prisma.RepuestoMantenimientoScalarFieldEnum[]
}

/**
 * Mantenimiento without action
 */
export type MantenimientoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
}
