
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MantenimientoRepuesto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MantenimientoRepuesto
 * 
 */
export type MantenimientoRepuestoModel = runtime.Types.Result.DefaultSelection<Prisma.$MantenimientoRepuestoPayload>

export type AggregateMantenimientoRepuesto = {
  _count: MantenimientoRepuestoCountAggregateOutputType | null
  _avg: MantenimientoRepuestoAvgAggregateOutputType | null
  _sum: MantenimientoRepuestoSumAggregateOutputType | null
  _min: MantenimientoRepuestoMinAggregateOutputType | null
  _max: MantenimientoRepuestoMaxAggregateOutputType | null
}

export type MantenimientoRepuestoAvgAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
}

export type MantenimientoRepuestoSumAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
}

export type MantenimientoRepuestoMinAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type MantenimientoRepuestoMaxAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type MantenimientoRepuestoCountAggregateOutputType = {
  id: number
  mantenimientoId: number
  repuestoId: number
  cantidad: number
  costoUnitario: number
  creadoEn: number
  _all: number
}


export type MantenimientoRepuestoAvgAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
}

export type MantenimientoRepuestoSumAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
}

export type MantenimientoRepuestoMinAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
}

export type MantenimientoRepuestoMaxAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
}

export type MantenimientoRepuestoCountAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
  _all?: true
}

export type MantenimientoRepuestoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MantenimientoRepuesto to aggregate.
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MantenimientoRepuestos to fetch.
   */
  orderBy?: Prisma.MantenimientoRepuestoOrderByWithRelationInput | Prisma.MantenimientoRepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MantenimientoRepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MantenimientoRepuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MantenimientoRepuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MantenimientoRepuestos
  **/
  _count?: true | MantenimientoRepuestoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MantenimientoRepuestoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MantenimientoRepuestoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MantenimientoRepuestoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MantenimientoRepuestoMaxAggregateInputType
}

export type GetMantenimientoRepuestoAggregateType<T extends MantenimientoRepuestoAggregateArgs> = {
      [P in keyof T & keyof AggregateMantenimientoRepuesto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMantenimientoRepuesto[P]>
    : Prisma.GetScalarType<T[P], AggregateMantenimientoRepuesto[P]>
}




export type MantenimientoRepuestoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MantenimientoRepuestoWhereInput
  orderBy?: Prisma.MantenimientoRepuestoOrderByWithAggregationInput | Prisma.MantenimientoRepuestoOrderByWithAggregationInput[]
  by: Prisma.MantenimientoRepuestoScalarFieldEnum[] | Prisma.MantenimientoRepuestoScalarFieldEnum
  having?: Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MantenimientoRepuestoCountAggregateInputType | true
  _avg?: MantenimientoRepuestoAvgAggregateInputType
  _sum?: MantenimientoRepuestoSumAggregateInputType
  _min?: MantenimientoRepuestoMinAggregateInputType
  _max?: MantenimientoRepuestoMaxAggregateInputType
}

export type MantenimientoRepuestoGroupByOutputType = {
  id: number
  mantenimientoId: number
  repuestoId: number
  cantidad: number
  costoUnitario: runtime.Decimal
  creadoEn: Date
  _count: MantenimientoRepuestoCountAggregateOutputType | null
  _avg: MantenimientoRepuestoAvgAggregateOutputType | null
  _sum: MantenimientoRepuestoSumAggregateOutputType | null
  _min: MantenimientoRepuestoMinAggregateOutputType | null
  _max: MantenimientoRepuestoMaxAggregateOutputType | null
}

export type GetMantenimientoRepuestoGroupByPayload<T extends MantenimientoRepuestoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MantenimientoRepuestoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MantenimientoRepuestoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MantenimientoRepuestoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MantenimientoRepuestoGroupByOutputType[P]>
      }
    >
  >



export type MantenimientoRepuestoWhereInput = {
  AND?: Prisma.MantenimientoRepuestoWhereInput | Prisma.MantenimientoRepuestoWhereInput[]
  OR?: Prisma.MantenimientoRepuestoWhereInput[]
  NOT?: Prisma.MantenimientoRepuestoWhereInput | Prisma.MantenimientoRepuestoWhereInput[]
  id?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  mantenimientoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  repuestoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  cantidad?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  costoUnitario?: Prisma.DecimalFilter<"MantenimientoRepuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"MantenimientoRepuesto"> | Date | string
  mantenimiento?: Prisma.XOR<Prisma.MantenimientoScalarRelationFilter, Prisma.MantenimientoWhereInput>
  repuesto?: Prisma.XOR<Prisma.RepuestoScalarRelationFilter, Prisma.RepuestoWhereInput>
}

export type MantenimientoRepuestoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  mantenimiento?: Prisma.MantenimientoOrderByWithRelationInput
  repuesto?: Prisma.RepuestoOrderByWithRelationInput
}

export type MantenimientoRepuestoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MantenimientoRepuestoWhereInput | Prisma.MantenimientoRepuestoWhereInput[]
  OR?: Prisma.MantenimientoRepuestoWhereInput[]
  NOT?: Prisma.MantenimientoRepuestoWhereInput | Prisma.MantenimientoRepuestoWhereInput[]
  mantenimientoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  repuestoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  cantidad?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  costoUnitario?: Prisma.DecimalFilter<"MantenimientoRepuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"MantenimientoRepuesto"> | Date | string
  mantenimiento?: Prisma.XOR<Prisma.MantenimientoScalarRelationFilter, Prisma.MantenimientoWhereInput>
  repuesto?: Prisma.XOR<Prisma.RepuestoScalarRelationFilter, Prisma.RepuestoWhereInput>
}, "id">

export type MantenimientoRepuestoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  _count?: Prisma.MantenimientoRepuestoCountOrderByAggregateInput
  _avg?: Prisma.MantenimientoRepuestoAvgOrderByAggregateInput
  _max?: Prisma.MantenimientoRepuestoMaxOrderByAggregateInput
  _min?: Prisma.MantenimientoRepuestoMinOrderByAggregateInput
  _sum?: Prisma.MantenimientoRepuestoSumOrderByAggregateInput
}

export type MantenimientoRepuestoScalarWhereWithAggregatesInput = {
  AND?: Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput | Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput[]
  OR?: Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput | Prisma.MantenimientoRepuestoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MantenimientoRepuesto"> | number
  mantenimientoId?: Prisma.IntWithAggregatesFilter<"MantenimientoRepuesto"> | number
  repuestoId?: Prisma.IntWithAggregatesFilter<"MantenimientoRepuesto"> | number
  cantidad?: Prisma.IntWithAggregatesFilter<"MantenimientoRepuesto"> | number
  costoUnitario?: Prisma.DecimalWithAggregatesFilter<"MantenimientoRepuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeWithAggregatesFilter<"MantenimientoRepuesto"> | Date | string
}

export type MantenimientoRepuestoCreateInput = {
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimiento: Prisma.MantenimientoCreateNestedOneWithoutRepuestosUtilizadosInput
  repuesto: Prisma.RepuestoCreateNestedOneWithoutMantenimientosInput
}

export type MantenimientoRepuestoUncheckedCreateInput = {
  id?: number
  mantenimientoId: number
  repuestoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoUpdateInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimiento?: Prisma.MantenimientoUpdateOneRequiredWithoutRepuestosUtilizadosNestedInput
  repuesto?: Prisma.RepuestoUpdateOneRequiredWithoutMantenimientosNestedInput
}

export type MantenimientoRepuestoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoCreateManyInput = {
  id?: number
  mantenimientoId: number
  repuestoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoUpdateManyMutationInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoListRelationFilter = {
  every?: Prisma.MantenimientoRepuestoWhereInput
  some?: Prisma.MantenimientoRepuestoWhereInput
  none?: Prisma.MantenimientoRepuestoWhereInput
}

export type MantenimientoRepuestoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MantenimientoRepuestoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type MantenimientoRepuestoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
}

export type MantenimientoRepuestoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type MantenimientoRepuestoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type MantenimientoRepuestoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
}

export type MantenimientoRepuestoCreateNestedManyWithoutMantenimientoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput> | Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyMantenimientoInputEnvelope
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
}

export type MantenimientoRepuestoUncheckedCreateNestedManyWithoutMantenimientoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput> | Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyMantenimientoInputEnvelope
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
}

export type MantenimientoRepuestoUpdateManyWithoutMantenimientoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput> | Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput[]
  upsert?: Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutMantenimientoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyMantenimientoInputEnvelope
  set?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  delete?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  update?: Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutMantenimientoInput[]
  updateMany?: Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutMantenimientoInput[]
  deleteMany?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
}

export type MantenimientoRepuestoUncheckedUpdateManyWithoutMantenimientoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput> | Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput[]
  upsert?: Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutMantenimientoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyMantenimientoInputEnvelope
  set?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  delete?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  update?: Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutMantenimientoInput[]
  updateMany?: Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutMantenimientoInput | Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutMantenimientoInput[]
  deleteMany?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
}

export type MantenimientoRepuestoCreateNestedManyWithoutRepuestoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput> | Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyRepuestoInputEnvelope
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
}

export type MantenimientoRepuestoUncheckedCreateNestedManyWithoutRepuestoInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput> | Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyRepuestoInputEnvelope
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
}

export type MantenimientoRepuestoUpdateManyWithoutRepuestoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput> | Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput[]
  upsert?: Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutRepuestoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyRepuestoInputEnvelope
  set?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  delete?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  update?: Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutRepuestoInput[]
  updateMany?: Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutRepuestoInput[]
  deleteMany?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
}

export type MantenimientoRepuestoUncheckedUpdateManyWithoutRepuestoNestedInput = {
  create?: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput> | Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput[] | Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput | Prisma.MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput[]
  upsert?: Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpsertWithWhereUniqueWithoutRepuestoInput[]
  createMany?: Prisma.MantenimientoRepuestoCreateManyRepuestoInputEnvelope
  set?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  disconnect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  delete?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  connect?: Prisma.MantenimientoRepuestoWhereUniqueInput | Prisma.MantenimientoRepuestoWhereUniqueInput[]
  update?: Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpdateWithWhereUniqueWithoutRepuestoInput[]
  updateMany?: Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutRepuestoInput | Prisma.MantenimientoRepuestoUpdateManyWithWhereWithoutRepuestoInput[]
  deleteMany?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
}

export type MantenimientoRepuestoCreateWithoutMantenimientoInput = {
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  repuesto: Prisma.RepuestoCreateNestedOneWithoutMantenimientosInput
}

export type MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput = {
  id?: number
  repuestoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoCreateOrConnectWithoutMantenimientoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  create: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput>
}

export type MantenimientoRepuestoCreateManyMantenimientoInputEnvelope = {
  data: Prisma.MantenimientoRepuestoCreateManyMantenimientoInput | Prisma.MantenimientoRepuestoCreateManyMantenimientoInput[]
  skipDuplicates?: boolean
}

export type MantenimientoRepuestoUpsertWithWhereUniqueWithoutMantenimientoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  update: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedUpdateWithoutMantenimientoInput>
  create: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutMantenimientoInput>
}

export type MantenimientoRepuestoUpdateWithWhereUniqueWithoutMantenimientoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateWithoutMantenimientoInput, Prisma.MantenimientoRepuestoUncheckedUpdateWithoutMantenimientoInput>
}

export type MantenimientoRepuestoUpdateManyWithWhereWithoutMantenimientoInput = {
  where: Prisma.MantenimientoRepuestoScalarWhereInput
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateManyMutationInput, Prisma.MantenimientoRepuestoUncheckedUpdateManyWithoutMantenimientoInput>
}

export type MantenimientoRepuestoScalarWhereInput = {
  AND?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
  OR?: Prisma.MantenimientoRepuestoScalarWhereInput[]
  NOT?: Prisma.MantenimientoRepuestoScalarWhereInput | Prisma.MantenimientoRepuestoScalarWhereInput[]
  id?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  mantenimientoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  repuestoId?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  cantidad?: Prisma.IntFilter<"MantenimientoRepuesto"> | number
  costoUnitario?: Prisma.DecimalFilter<"MantenimientoRepuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"MantenimientoRepuesto"> | Date | string
}

export type MantenimientoRepuestoCreateWithoutRepuestoInput = {
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimiento: Prisma.MantenimientoCreateNestedOneWithoutRepuestosUtilizadosInput
}

export type MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput = {
  id?: number
  mantenimientoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoCreateOrConnectWithoutRepuestoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  create: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput>
}

export type MantenimientoRepuestoCreateManyRepuestoInputEnvelope = {
  data: Prisma.MantenimientoRepuestoCreateManyRepuestoInput | Prisma.MantenimientoRepuestoCreateManyRepuestoInput[]
  skipDuplicates?: boolean
}

export type MantenimientoRepuestoUpsertWithWhereUniqueWithoutRepuestoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  update: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedUpdateWithoutRepuestoInput>
  create: Prisma.XOR<Prisma.MantenimientoRepuestoCreateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedCreateWithoutRepuestoInput>
}

export type MantenimientoRepuestoUpdateWithWhereUniqueWithoutRepuestoInput = {
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateWithoutRepuestoInput, Prisma.MantenimientoRepuestoUncheckedUpdateWithoutRepuestoInput>
}

export type MantenimientoRepuestoUpdateManyWithWhereWithoutRepuestoInput = {
  where: Prisma.MantenimientoRepuestoScalarWhereInput
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateManyMutationInput, Prisma.MantenimientoRepuestoUncheckedUpdateManyWithoutRepuestoInput>
}

export type MantenimientoRepuestoCreateManyMantenimientoInput = {
  id?: number
  repuestoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoUpdateWithoutMantenimientoInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repuesto?: Prisma.RepuestoUpdateOneRequiredWithoutMantenimientosNestedInput
}

export type MantenimientoRepuestoUncheckedUpdateWithoutMantenimientoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoUncheckedUpdateManyWithoutMantenimientoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoCreateManyRepuestoInput = {
  id?: number
  mantenimientoId: number
  cantidad?: number
  costoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type MantenimientoRepuestoUpdateWithoutRepuestoInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimiento?: Prisma.MantenimientoUpdateOneRequiredWithoutRepuestosUtilizadosNestedInput
}

export type MantenimientoRepuestoUncheckedUpdateWithoutRepuestoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MantenimientoRepuestoUncheckedUpdateManyWithoutRepuestoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MantenimientoRepuestoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mantenimientoId?: boolean
  repuestoId?: boolean
  cantidad?: boolean
  costoUnitario?: boolean
  creadoEn?: boolean
  mantenimiento?: boolean | Prisma.MantenimientoDefaultArgs<ExtArgs>
  repuesto?: boolean | Prisma.RepuestoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mantenimientoRepuesto"]>



export type MantenimientoRepuestoSelectScalar = {
  id?: boolean
  mantenimientoId?: boolean
  repuestoId?: boolean
  cantidad?: boolean
  costoUnitario?: boolean
  creadoEn?: boolean
}

export type MantenimientoRepuestoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mantenimientoId" | "repuestoId" | "cantidad" | "costoUnitario" | "creadoEn", ExtArgs["result"]["mantenimientoRepuesto"]>
export type MantenimientoRepuestoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mantenimiento?: boolean | Prisma.MantenimientoDefaultArgs<ExtArgs>
  repuesto?: boolean | Prisma.RepuestoDefaultArgs<ExtArgs>
}

export type $MantenimientoRepuestoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MantenimientoRepuesto"
  objects: {
    mantenimiento: Prisma.$MantenimientoPayload<ExtArgs>
    repuesto: Prisma.$RepuestoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    mantenimientoId: number
    repuestoId: number
    cantidad: number
    costoUnitario: runtime.Decimal
    creadoEn: Date
  }, ExtArgs["result"]["mantenimientoRepuesto"]>
  composites: {}
}

export type MantenimientoRepuestoGetPayload<S extends boolean | null | undefined | MantenimientoRepuestoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload, S>

export type MantenimientoRepuestoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MantenimientoRepuestoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MantenimientoRepuestoCountAggregateInputType | true
  }

export interface MantenimientoRepuestoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MantenimientoRepuesto'], meta: { name: 'MantenimientoRepuesto' } }
  /**
   * Find zero or one MantenimientoRepuesto that matches the filter.
   * @param {MantenimientoRepuestoFindUniqueArgs} args - Arguments to find a MantenimientoRepuesto
   * @example
   * // Get one MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MantenimientoRepuestoFindUniqueArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MantenimientoRepuesto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MantenimientoRepuestoFindUniqueOrThrowArgs} args - Arguments to find a MantenimientoRepuesto
   * @example
   * // Get one MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MantenimientoRepuestoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MantenimientoRepuesto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoFindFirstArgs} args - Arguments to find a MantenimientoRepuesto
   * @example
   * // Get one MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MantenimientoRepuestoFindFirstArgs>(args?: Prisma.SelectSubset<T, MantenimientoRepuestoFindFirstArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MantenimientoRepuesto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoFindFirstOrThrowArgs} args - Arguments to find a MantenimientoRepuesto
   * @example
   * // Get one MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MantenimientoRepuestoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MantenimientoRepuestoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MantenimientoRepuestos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MantenimientoRepuestos
   * const mantenimientoRepuestos = await prisma.mantenimientoRepuesto.findMany()
   * 
   * // Get first 10 MantenimientoRepuestos
   * const mantenimientoRepuestos = await prisma.mantenimientoRepuesto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mantenimientoRepuestoWithIdOnly = await prisma.mantenimientoRepuesto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MantenimientoRepuestoFindManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoRepuestoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MantenimientoRepuesto.
   * @param {MantenimientoRepuestoCreateArgs} args - Arguments to create a MantenimientoRepuesto.
   * @example
   * // Create one MantenimientoRepuesto
   * const MantenimientoRepuesto = await prisma.mantenimientoRepuesto.create({
   *   data: {
   *     // ... data to create a MantenimientoRepuesto
   *   }
   * })
   * 
   */
  create<T extends MantenimientoRepuestoCreateArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoCreateArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MantenimientoRepuestos.
   * @param {MantenimientoRepuestoCreateManyArgs} args - Arguments to create many MantenimientoRepuestos.
   * @example
   * // Create many MantenimientoRepuestos
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MantenimientoRepuestoCreateManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoRepuestoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a MantenimientoRepuesto.
   * @param {MantenimientoRepuestoDeleteArgs} args - Arguments to delete one MantenimientoRepuesto.
   * @example
   * // Delete one MantenimientoRepuesto
   * const MantenimientoRepuesto = await prisma.mantenimientoRepuesto.delete({
   *   where: {
   *     // ... filter to delete one MantenimientoRepuesto
   *   }
   * })
   * 
   */
  delete<T extends MantenimientoRepuestoDeleteArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoDeleteArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MantenimientoRepuesto.
   * @param {MantenimientoRepuestoUpdateArgs} args - Arguments to update one MantenimientoRepuesto.
   * @example
   * // Update one MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MantenimientoRepuestoUpdateArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoUpdateArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MantenimientoRepuestos.
   * @param {MantenimientoRepuestoDeleteManyArgs} args - Arguments to filter MantenimientoRepuestos to delete.
   * @example
   * // Delete a few MantenimientoRepuestos
   * const { count } = await prisma.mantenimientoRepuesto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MantenimientoRepuestoDeleteManyArgs>(args?: Prisma.SelectSubset<T, MantenimientoRepuestoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MantenimientoRepuestos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MantenimientoRepuestos
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MantenimientoRepuestoUpdateManyArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one MantenimientoRepuesto.
   * @param {MantenimientoRepuestoUpsertArgs} args - Arguments to update or create a MantenimientoRepuesto.
   * @example
   * // Update or create a MantenimientoRepuesto
   * const mantenimientoRepuesto = await prisma.mantenimientoRepuesto.upsert({
   *   create: {
   *     // ... data to create a MantenimientoRepuesto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MantenimientoRepuesto we want to update
   *   }
   * })
   */
  upsert<T extends MantenimientoRepuestoUpsertArgs>(args: Prisma.SelectSubset<T, MantenimientoRepuestoUpsertArgs<ExtArgs>>): Prisma.Prisma__MantenimientoRepuestoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoRepuestoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MantenimientoRepuestos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoCountArgs} args - Arguments to filter MantenimientoRepuestos to count.
   * @example
   * // Count the number of MantenimientoRepuestos
   * const count = await prisma.mantenimientoRepuesto.count({
   *   where: {
   *     // ... the filter for the MantenimientoRepuestos we want to count
   *   }
   * })
  **/
  count<T extends MantenimientoRepuestoCountArgs>(
    args?: Prisma.Subset<T, MantenimientoRepuestoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MantenimientoRepuestoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MantenimientoRepuesto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MantenimientoRepuestoAggregateArgs>(args: Prisma.Subset<T, MantenimientoRepuestoAggregateArgs>): Prisma.PrismaPromise<GetMantenimientoRepuestoAggregateType<T>>

  /**
   * Group by MantenimientoRepuesto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MantenimientoRepuestoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MantenimientoRepuestoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MantenimientoRepuestoGroupByArgs['orderBy'] }
      : { orderBy?: MantenimientoRepuestoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MantenimientoRepuestoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMantenimientoRepuestoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MantenimientoRepuesto model
 */
readonly fields: MantenimientoRepuestoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MantenimientoRepuesto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MantenimientoRepuestoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mantenimiento<T extends Prisma.MantenimientoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MantenimientoDefaultArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  repuesto<T extends Prisma.RepuestoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RepuestoDefaultArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MantenimientoRepuesto model
 */
export interface MantenimientoRepuestoFieldRefs {
  readonly id: Prisma.FieldRef<"MantenimientoRepuesto", 'Int'>
  readonly mantenimientoId: Prisma.FieldRef<"MantenimientoRepuesto", 'Int'>
  readonly repuestoId: Prisma.FieldRef<"MantenimientoRepuesto", 'Int'>
  readonly cantidad: Prisma.FieldRef<"MantenimientoRepuesto", 'Int'>
  readonly costoUnitario: Prisma.FieldRef<"MantenimientoRepuesto", 'Decimal'>
  readonly creadoEn: Prisma.FieldRef<"MantenimientoRepuesto", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MantenimientoRepuesto findUnique
 */
export type MantenimientoRepuestoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter, which MantenimientoRepuesto to fetch.
   */
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
}

/**
 * MantenimientoRepuesto findUniqueOrThrow
 */
export type MantenimientoRepuestoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter, which MantenimientoRepuesto to fetch.
   */
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
}

/**
 * MantenimientoRepuesto findFirst
 */
export type MantenimientoRepuestoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter, which MantenimientoRepuesto to fetch.
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MantenimientoRepuestos to fetch.
   */
  orderBy?: Prisma.MantenimientoRepuestoOrderByWithRelationInput | Prisma.MantenimientoRepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MantenimientoRepuestos.
   */
  cursor?: Prisma.MantenimientoRepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MantenimientoRepuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MantenimientoRepuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MantenimientoRepuestos.
   */
  distinct?: Prisma.MantenimientoRepuestoScalarFieldEnum | Prisma.MantenimientoRepuestoScalarFieldEnum[]
}

/**
 * MantenimientoRepuesto findFirstOrThrow
 */
export type MantenimientoRepuestoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter, which MantenimientoRepuesto to fetch.
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MantenimientoRepuestos to fetch.
   */
  orderBy?: Prisma.MantenimientoRepuestoOrderByWithRelationInput | Prisma.MantenimientoRepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MantenimientoRepuestos.
   */
  cursor?: Prisma.MantenimientoRepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MantenimientoRepuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MantenimientoRepuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MantenimientoRepuestos.
   */
  distinct?: Prisma.MantenimientoRepuestoScalarFieldEnum | Prisma.MantenimientoRepuestoScalarFieldEnum[]
}

/**
 * MantenimientoRepuesto findMany
 */
export type MantenimientoRepuestoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter, which MantenimientoRepuestos to fetch.
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MantenimientoRepuestos to fetch.
   */
  orderBy?: Prisma.MantenimientoRepuestoOrderByWithRelationInput | Prisma.MantenimientoRepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MantenimientoRepuestos.
   */
  cursor?: Prisma.MantenimientoRepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MantenimientoRepuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MantenimientoRepuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MantenimientoRepuestos.
   */
  distinct?: Prisma.MantenimientoRepuestoScalarFieldEnum | Prisma.MantenimientoRepuestoScalarFieldEnum[]
}

/**
 * MantenimientoRepuesto create
 */
export type MantenimientoRepuestoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * The data needed to create a MantenimientoRepuesto.
   */
  data: Prisma.XOR<Prisma.MantenimientoRepuestoCreateInput, Prisma.MantenimientoRepuestoUncheckedCreateInput>
}

/**
 * MantenimientoRepuesto createMany
 */
export type MantenimientoRepuestoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MantenimientoRepuestos.
   */
  data: Prisma.MantenimientoRepuestoCreateManyInput | Prisma.MantenimientoRepuestoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MantenimientoRepuesto update
 */
export type MantenimientoRepuestoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * The data needed to update a MantenimientoRepuesto.
   */
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateInput, Prisma.MantenimientoRepuestoUncheckedUpdateInput>
  /**
   * Choose, which MantenimientoRepuesto to update.
   */
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
}

/**
 * MantenimientoRepuesto updateMany
 */
export type MantenimientoRepuestoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MantenimientoRepuestos.
   */
  data: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateManyMutationInput, Prisma.MantenimientoRepuestoUncheckedUpdateManyInput>
  /**
   * Filter which MantenimientoRepuestos to update
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * Limit how many MantenimientoRepuestos to update.
   */
  limit?: number
}

/**
 * MantenimientoRepuesto upsert
 */
export type MantenimientoRepuestoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * The filter to search for the MantenimientoRepuesto to update in case it exists.
   */
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
  /**
   * In case the MantenimientoRepuesto found by the `where` argument doesn't exist, create a new MantenimientoRepuesto with this data.
   */
  create: Prisma.XOR<Prisma.MantenimientoRepuestoCreateInput, Prisma.MantenimientoRepuestoUncheckedCreateInput>
  /**
   * In case the MantenimientoRepuesto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MantenimientoRepuestoUpdateInput, Prisma.MantenimientoRepuestoUncheckedUpdateInput>
}

/**
 * MantenimientoRepuesto delete
 */
export type MantenimientoRepuestoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
  /**
   * Filter which MantenimientoRepuesto to delete.
   */
  where: Prisma.MantenimientoRepuestoWhereUniqueInput
}

/**
 * MantenimientoRepuesto deleteMany
 */
export type MantenimientoRepuestoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MantenimientoRepuestos to delete
   */
  where?: Prisma.MantenimientoRepuestoWhereInput
  /**
   * Limit how many MantenimientoRepuestos to delete.
   */
  limit?: number
}

/**
 * MantenimientoRepuesto without action
 */
export type MantenimientoRepuestoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MantenimientoRepuesto
   */
  select?: Prisma.MantenimientoRepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MantenimientoRepuesto
   */
  omit?: Prisma.MantenimientoRepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoRepuestoInclude<ExtArgs> | null
}
