
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Repuesto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Repuesto
 * 
 */
export type RepuestoModel = runtime.Types.Result.DefaultSelection<Prisma.$RepuestoPayload>

export type AggregateRepuesto = {
  _count: RepuestoCountAggregateOutputType | null
  _avg: RepuestoAvgAggregateOutputType | null
  _sum: RepuestoSumAggregateOutputType | null
  _min: RepuestoMinAggregateOutputType | null
  _max: RepuestoMaxAggregateOutputType | null
}

export type RepuestoAvgAggregateOutputType = {
  id: number | null
  stock: number | null
  precioUnitario: runtime.Decimal | null
}

export type RepuestoSumAggregateOutputType = {
  id: number | null
  stock: number | null
  precioUnitario: runtime.Decimal | null
}

export type RepuestoMinAggregateOutputType = {
  id: number | null
  codigo: string | null
  nombre: string | null
  descripcion: string | null
  stock: number | null
  precioUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type RepuestoMaxAggregateOutputType = {
  id: number | null
  codigo: string | null
  nombre: string | null
  descripcion: string | null
  stock: number | null
  precioUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type RepuestoCountAggregateOutputType = {
  id: number
  codigo: number
  nombre: number
  descripcion: number
  stock: number
  precioUnitario: number
  creadoEn: number
  _all: number
}


export type RepuestoAvgAggregateInputType = {
  id?: true
  stock?: true
  precioUnitario?: true
}

export type RepuestoSumAggregateInputType = {
  id?: true
  stock?: true
  precioUnitario?: true
}

export type RepuestoMinAggregateInputType = {
  id?: true
  codigo?: true
  nombre?: true
  descripcion?: true
  stock?: true
  precioUnitario?: true
  creadoEn?: true
}

export type RepuestoMaxAggregateInputType = {
  id?: true
  codigo?: true
  nombre?: true
  descripcion?: true
  stock?: true
  precioUnitario?: true
  creadoEn?: true
}

export type RepuestoCountAggregateInputType = {
  id?: true
  codigo?: true
  nombre?: true
  descripcion?: true
  stock?: true
  precioUnitario?: true
  creadoEn?: true
  _all?: true
}

export type RepuestoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Repuesto to aggregate.
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Repuestos to fetch.
   */
  orderBy?: Prisma.RepuestoOrderByWithRelationInput | Prisma.RepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Repuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Repuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Repuestos
  **/
  _count?: true | RepuestoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RepuestoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RepuestoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RepuestoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RepuestoMaxAggregateInputType
}

export type GetRepuestoAggregateType<T extends RepuestoAggregateArgs> = {
      [P in keyof T & keyof AggregateRepuesto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRepuesto[P]>
    : Prisma.GetScalarType<T[P], AggregateRepuesto[P]>
}




export type RepuestoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RepuestoWhereInput
  orderBy?: Prisma.RepuestoOrderByWithAggregationInput | Prisma.RepuestoOrderByWithAggregationInput[]
  by: Prisma.RepuestoScalarFieldEnum[] | Prisma.RepuestoScalarFieldEnum
  having?: Prisma.RepuestoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RepuestoCountAggregateInputType | true
  _avg?: RepuestoAvgAggregateInputType
  _sum?: RepuestoSumAggregateInputType
  _min?: RepuestoMinAggregateInputType
  _max?: RepuestoMaxAggregateInputType
}

export type RepuestoGroupByOutputType = {
  id: number
  codigo: string
  nombre: string
  descripcion: string | null
  stock: number
  precioUnitario: runtime.Decimal
  creadoEn: Date
  _count: RepuestoCountAggregateOutputType | null
  _avg: RepuestoAvgAggregateOutputType | null
  _sum: RepuestoSumAggregateOutputType | null
  _min: RepuestoMinAggregateOutputType | null
  _max: RepuestoMaxAggregateOutputType | null
}

export type GetRepuestoGroupByPayload<T extends RepuestoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RepuestoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RepuestoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RepuestoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RepuestoGroupByOutputType[P]>
      }
    >
  >



export type RepuestoWhereInput = {
  AND?: Prisma.RepuestoWhereInput | Prisma.RepuestoWhereInput[]
  OR?: Prisma.RepuestoWhereInput[]
  NOT?: Prisma.RepuestoWhereInput | Prisma.RepuestoWhereInput[]
  id?: Prisma.IntFilter<"Repuesto"> | number
  codigo?: Prisma.StringFilter<"Repuesto"> | string
  nombre?: Prisma.StringFilter<"Repuesto"> | string
  descripcion?: Prisma.StringNullableFilter<"Repuesto"> | string | null
  stock?: Prisma.IntFilter<"Repuesto"> | number
  precioUnitario?: Prisma.DecimalFilter<"Repuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"Repuesto"> | Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoListRelationFilter
}

export type RepuestoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  codigo?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  mantenimientos?: Prisma.RepuestoMantenimientoOrderByRelationAggregateInput
  _relevance?: Prisma.RepuestoOrderByRelevanceInput
}

export type RepuestoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  codigo?: string
  AND?: Prisma.RepuestoWhereInput | Prisma.RepuestoWhereInput[]
  OR?: Prisma.RepuestoWhereInput[]
  NOT?: Prisma.RepuestoWhereInput | Prisma.RepuestoWhereInput[]
  nombre?: Prisma.StringFilter<"Repuesto"> | string
  descripcion?: Prisma.StringNullableFilter<"Repuesto"> | string | null
  stock?: Prisma.IntFilter<"Repuesto"> | number
  precioUnitario?: Prisma.DecimalFilter<"Repuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"Repuesto"> | Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoListRelationFilter
}, "id" | "codigo">

export type RepuestoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  codigo?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  _count?: Prisma.RepuestoCountOrderByAggregateInput
  _avg?: Prisma.RepuestoAvgOrderByAggregateInput
  _max?: Prisma.RepuestoMaxOrderByAggregateInput
  _min?: Prisma.RepuestoMinOrderByAggregateInput
  _sum?: Prisma.RepuestoSumOrderByAggregateInput
}

export type RepuestoScalarWhereWithAggregatesInput = {
  AND?: Prisma.RepuestoScalarWhereWithAggregatesInput | Prisma.RepuestoScalarWhereWithAggregatesInput[]
  OR?: Prisma.RepuestoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RepuestoScalarWhereWithAggregatesInput | Prisma.RepuestoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Repuesto"> | number
  codigo?: Prisma.StringWithAggregatesFilter<"Repuesto"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"Repuesto"> | string
  descripcion?: Prisma.StringNullableWithAggregatesFilter<"Repuesto"> | string | null
  stock?: Prisma.IntWithAggregatesFilter<"Repuesto"> | number
  precioUnitario?: Prisma.DecimalWithAggregatesFilter<"Repuesto"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeWithAggregatesFilter<"Repuesto"> | Date | string
}

export type RepuestoCreateInput = {
  codigo: string
  nombre: string
  descripcion?: string | null
  stock?: number
  precioUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoCreateNestedManyWithoutRepuestoInput
}

export type RepuestoUncheckedCreateInput = {
  id?: number
  codigo: string
  nombre: string
  descripcion?: string | null
  stock?: number
  precioUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoUncheckedCreateNestedManyWithoutRepuestoInput
}

export type RepuestoUpdateInput = {
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoUpdateManyWithoutRepuestoNestedInput
}

export type RepuestoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutRepuestoNestedInput
}

export type RepuestoCreateManyInput = {
  id?: number
  codigo: string
  nombre: string
  descripcion?: string | null
  stock?: number
  precioUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoUpdateManyMutationInput = {
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoOrderByRelevanceInput = {
  fields: Prisma.RepuestoOrderByRelevanceFieldEnum | Prisma.RepuestoOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RepuestoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  codigo?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
}

export type RepuestoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  codigo?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  codigo?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  precioUnitario?: Prisma.SortOrder
}

export type RepuestoScalarRelationFilter = {
  is?: Prisma.RepuestoWhereInput
  isNot?: Prisma.RepuestoWhereInput
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type RepuestoCreateNestedOneWithoutMantenimientosInput = {
  create?: Prisma.XOR<Prisma.RepuestoCreateWithoutMantenimientosInput, Prisma.RepuestoUncheckedCreateWithoutMantenimientosInput>
  connectOrCreate?: Prisma.RepuestoCreateOrConnectWithoutMantenimientosInput
  connect?: Prisma.RepuestoWhereUniqueInput
}

export type RepuestoUpdateOneRequiredWithoutMantenimientosNestedInput = {
  create?: Prisma.XOR<Prisma.RepuestoCreateWithoutMantenimientosInput, Prisma.RepuestoUncheckedCreateWithoutMantenimientosInput>
  connectOrCreate?: Prisma.RepuestoCreateOrConnectWithoutMantenimientosInput
  upsert?: Prisma.RepuestoUpsertWithoutMantenimientosInput
  connect?: Prisma.RepuestoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RepuestoUpdateToOneWithWhereWithoutMantenimientosInput, Prisma.RepuestoUpdateWithoutMantenimientosInput>, Prisma.RepuestoUncheckedUpdateWithoutMantenimientosInput>
}

export type RepuestoCreateWithoutMantenimientosInput = {
  codigo: string
  nombre: string
  descripcion?: string | null
  stock?: number
  precioUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoUncheckedCreateWithoutMantenimientosInput = {
  id?: number
  codigo: string
  nombre: string
  descripcion?: string | null
  stock?: number
  precioUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoCreateOrConnectWithoutMantenimientosInput = {
  where: Prisma.RepuestoWhereUniqueInput
  create: Prisma.XOR<Prisma.RepuestoCreateWithoutMantenimientosInput, Prisma.RepuestoUncheckedCreateWithoutMantenimientosInput>
}

export type RepuestoUpsertWithoutMantenimientosInput = {
  update: Prisma.XOR<Prisma.RepuestoUpdateWithoutMantenimientosInput, Prisma.RepuestoUncheckedUpdateWithoutMantenimientosInput>
  create: Prisma.XOR<Prisma.RepuestoCreateWithoutMantenimientosInput, Prisma.RepuestoUncheckedCreateWithoutMantenimientosInput>
  where?: Prisma.RepuestoWhereInput
}

export type RepuestoUpdateToOneWithWhereWithoutMantenimientosInput = {
  where?: Prisma.RepuestoWhereInput
  data: Prisma.XOR<Prisma.RepuestoUpdateWithoutMantenimientosInput, Prisma.RepuestoUncheckedUpdateWithoutMantenimientosInput>
}

export type RepuestoUpdateWithoutMantenimientosInput = {
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoUncheckedUpdateWithoutMantenimientosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  codigo?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stock?: Prisma.IntFieldUpdateOperationsInput | number
  precioUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type RepuestoCountOutputType
 */

export type RepuestoCountOutputType = {
  mantenimientos: number
}

export type RepuestoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mantenimientos?: boolean | RepuestoCountOutputTypeCountMantenimientosArgs
}

/**
 * RepuestoCountOutputType without action
 */
export type RepuestoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoCountOutputType
   */
  select?: Prisma.RepuestoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RepuestoCountOutputType without action
 */
export type RepuestoCountOutputTypeCountMantenimientosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RepuestoMantenimientoWhereInput
}


export type RepuestoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  codigo?: boolean
  nombre?: boolean
  descripcion?: boolean
  stock?: boolean
  precioUnitario?: boolean
  creadoEn?: boolean
  mantenimientos?: boolean | Prisma.Repuesto$mantenimientosArgs<ExtArgs>
  _count?: boolean | Prisma.RepuestoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["repuesto"]>



export type RepuestoSelectScalar = {
  id?: boolean
  codigo?: boolean
  nombre?: boolean
  descripcion?: boolean
  stock?: boolean
  precioUnitario?: boolean
  creadoEn?: boolean
}

export type RepuestoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "codigo" | "nombre" | "descripcion" | "stock" | "precioUnitario" | "creadoEn", ExtArgs["result"]["repuesto"]>
export type RepuestoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mantenimientos?: boolean | Prisma.Repuesto$mantenimientosArgs<ExtArgs>
  _count?: boolean | Prisma.RepuestoCountOutputTypeDefaultArgs<ExtArgs>
}

export type $RepuestoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Repuesto"
  objects: {
    mantenimientos: Prisma.$RepuestoMantenimientoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    codigo: string
    nombre: string
    descripcion: string | null
    stock: number
    precioUnitario: runtime.Decimal
    creadoEn: Date
  }, ExtArgs["result"]["repuesto"]>
  composites: {}
}

export type RepuestoGetPayload<S extends boolean | null | undefined | RepuestoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RepuestoPayload, S>

export type RepuestoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RepuestoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RepuestoCountAggregateInputType | true
  }

export interface RepuestoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Repuesto'], meta: { name: 'Repuesto' } }
  /**
   * Find zero or one Repuesto that matches the filter.
   * @param {RepuestoFindUniqueArgs} args - Arguments to find a Repuesto
   * @example
   * // Get one Repuesto
   * const repuesto = await prisma.repuesto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RepuestoFindUniqueArgs>(args: Prisma.SelectSubset<T, RepuestoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Repuesto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RepuestoFindUniqueOrThrowArgs} args - Arguments to find a Repuesto
   * @example
   * // Get one Repuesto
   * const repuesto = await prisma.repuesto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RepuestoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RepuestoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Repuesto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoFindFirstArgs} args - Arguments to find a Repuesto
   * @example
   * // Get one Repuesto
   * const repuesto = await prisma.repuesto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RepuestoFindFirstArgs>(args?: Prisma.SelectSubset<T, RepuestoFindFirstArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Repuesto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoFindFirstOrThrowArgs} args - Arguments to find a Repuesto
   * @example
   * // Get one Repuesto
   * const repuesto = await prisma.repuesto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RepuestoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RepuestoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Repuestos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Repuestos
   * const repuestos = await prisma.repuesto.findMany()
   * 
   * // Get first 10 Repuestos
   * const repuestos = await prisma.repuesto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const repuestoWithIdOnly = await prisma.repuesto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RepuestoFindManyArgs>(args?: Prisma.SelectSubset<T, RepuestoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Repuesto.
   * @param {RepuestoCreateArgs} args - Arguments to create a Repuesto.
   * @example
   * // Create one Repuesto
   * const Repuesto = await prisma.repuesto.create({
   *   data: {
   *     // ... data to create a Repuesto
   *   }
   * })
   * 
   */
  create<T extends RepuestoCreateArgs>(args: Prisma.SelectSubset<T, RepuestoCreateArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Repuestos.
   * @param {RepuestoCreateManyArgs} args - Arguments to create many Repuestos.
   * @example
   * // Create many Repuestos
   * const repuesto = await prisma.repuesto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RepuestoCreateManyArgs>(args?: Prisma.SelectSubset<T, RepuestoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Repuesto.
   * @param {RepuestoDeleteArgs} args - Arguments to delete one Repuesto.
   * @example
   * // Delete one Repuesto
   * const Repuesto = await prisma.repuesto.delete({
   *   where: {
   *     // ... filter to delete one Repuesto
   *   }
   * })
   * 
   */
  delete<T extends RepuestoDeleteArgs>(args: Prisma.SelectSubset<T, RepuestoDeleteArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Repuesto.
   * @param {RepuestoUpdateArgs} args - Arguments to update one Repuesto.
   * @example
   * // Update one Repuesto
   * const repuesto = await prisma.repuesto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RepuestoUpdateArgs>(args: Prisma.SelectSubset<T, RepuestoUpdateArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Repuestos.
   * @param {RepuestoDeleteManyArgs} args - Arguments to filter Repuestos to delete.
   * @example
   * // Delete a few Repuestos
   * const { count } = await prisma.repuesto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RepuestoDeleteManyArgs>(args?: Prisma.SelectSubset<T, RepuestoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Repuestos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Repuestos
   * const repuesto = await prisma.repuesto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RepuestoUpdateManyArgs>(args: Prisma.SelectSubset<T, RepuestoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Repuesto.
   * @param {RepuestoUpsertArgs} args - Arguments to update or create a Repuesto.
   * @example
   * // Update or create a Repuesto
   * const repuesto = await prisma.repuesto.upsert({
   *   create: {
   *     // ... data to create a Repuesto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Repuesto we want to update
   *   }
   * })
   */
  upsert<T extends RepuestoUpsertArgs>(args: Prisma.SelectSubset<T, RepuestoUpsertArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Repuestos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoCountArgs} args - Arguments to filter Repuestos to count.
   * @example
   * // Count the number of Repuestos
   * const count = await prisma.repuesto.count({
   *   where: {
   *     // ... the filter for the Repuestos we want to count
   *   }
   * })
  **/
  count<T extends RepuestoCountArgs>(
    args?: Prisma.Subset<T, RepuestoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RepuestoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Repuesto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RepuestoAggregateArgs>(args: Prisma.Subset<T, RepuestoAggregateArgs>): Prisma.PrismaPromise<GetRepuestoAggregateType<T>>

  /**
   * Group by Repuesto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RepuestoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RepuestoGroupByArgs['orderBy'] }
      : { orderBy?: RepuestoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RepuestoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRepuestoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Repuesto model
 */
readonly fields: RepuestoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Repuesto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RepuestoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mantenimientos<T extends Prisma.Repuesto$mantenimientosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Repuesto$mantenimientosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Repuesto model
 */
export interface RepuestoFieldRefs {
  readonly id: Prisma.FieldRef<"Repuesto", 'Int'>
  readonly codigo: Prisma.FieldRef<"Repuesto", 'String'>
  readonly nombre: Prisma.FieldRef<"Repuesto", 'String'>
  readonly descripcion: Prisma.FieldRef<"Repuesto", 'String'>
  readonly stock: Prisma.FieldRef<"Repuesto", 'Int'>
  readonly precioUnitario: Prisma.FieldRef<"Repuesto", 'Decimal'>
  readonly creadoEn: Prisma.FieldRef<"Repuesto", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Repuesto findUnique
 */
export type RepuestoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter, which Repuesto to fetch.
   */
  where: Prisma.RepuestoWhereUniqueInput
}

/**
 * Repuesto findUniqueOrThrow
 */
export type RepuestoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter, which Repuesto to fetch.
   */
  where: Prisma.RepuestoWhereUniqueInput
}

/**
 * Repuesto findFirst
 */
export type RepuestoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter, which Repuesto to fetch.
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Repuestos to fetch.
   */
  orderBy?: Prisma.RepuestoOrderByWithRelationInput | Prisma.RepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Repuestos.
   */
  cursor?: Prisma.RepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Repuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Repuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Repuestos.
   */
  distinct?: Prisma.RepuestoScalarFieldEnum | Prisma.RepuestoScalarFieldEnum[]
}

/**
 * Repuesto findFirstOrThrow
 */
export type RepuestoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter, which Repuesto to fetch.
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Repuestos to fetch.
   */
  orderBy?: Prisma.RepuestoOrderByWithRelationInput | Prisma.RepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Repuestos.
   */
  cursor?: Prisma.RepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Repuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Repuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Repuestos.
   */
  distinct?: Prisma.RepuestoScalarFieldEnum | Prisma.RepuestoScalarFieldEnum[]
}

/**
 * Repuesto findMany
 */
export type RepuestoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter, which Repuestos to fetch.
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Repuestos to fetch.
   */
  orderBy?: Prisma.RepuestoOrderByWithRelationInput | Prisma.RepuestoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Repuestos.
   */
  cursor?: Prisma.RepuestoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Repuestos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Repuestos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Repuestos.
   */
  distinct?: Prisma.RepuestoScalarFieldEnum | Prisma.RepuestoScalarFieldEnum[]
}

/**
 * Repuesto create
 */
export type RepuestoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * The data needed to create a Repuesto.
   */
  data: Prisma.XOR<Prisma.RepuestoCreateInput, Prisma.RepuestoUncheckedCreateInput>
}

/**
 * Repuesto createMany
 */
export type RepuestoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Repuestos.
   */
  data: Prisma.RepuestoCreateManyInput | Prisma.RepuestoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Repuesto update
 */
export type RepuestoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * The data needed to update a Repuesto.
   */
  data: Prisma.XOR<Prisma.RepuestoUpdateInput, Prisma.RepuestoUncheckedUpdateInput>
  /**
   * Choose, which Repuesto to update.
   */
  where: Prisma.RepuestoWhereUniqueInput
}

/**
 * Repuesto updateMany
 */
export type RepuestoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Repuestos.
   */
  data: Prisma.XOR<Prisma.RepuestoUpdateManyMutationInput, Prisma.RepuestoUncheckedUpdateManyInput>
  /**
   * Filter which Repuestos to update
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * Limit how many Repuestos to update.
   */
  limit?: number
}

/**
 * Repuesto upsert
 */
export type RepuestoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * The filter to search for the Repuesto to update in case it exists.
   */
  where: Prisma.RepuestoWhereUniqueInput
  /**
   * In case the Repuesto found by the `where` argument doesn't exist, create a new Repuesto with this data.
   */
  create: Prisma.XOR<Prisma.RepuestoCreateInput, Prisma.RepuestoUncheckedCreateInput>
  /**
   * In case the Repuesto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RepuestoUpdateInput, Prisma.RepuestoUncheckedUpdateInput>
}

/**
 * Repuesto delete
 */
export type RepuestoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
  /**
   * Filter which Repuesto to delete.
   */
  where: Prisma.RepuestoWhereUniqueInput
}

/**
 * Repuesto deleteMany
 */
export type RepuestoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Repuestos to delete
   */
  where?: Prisma.RepuestoWhereInput
  /**
   * Limit how many Repuestos to delete.
   */
  limit?: number
}

/**
 * Repuesto.mantenimientos
 */
export type Repuesto$mantenimientosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  where?: Prisma.RepuestoMantenimientoWhereInput
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RepuestoMantenimientoScalarFieldEnum | Prisma.RepuestoMantenimientoScalarFieldEnum[]
}

/**
 * Repuesto without action
 */
export type RepuestoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repuesto
   */
  select?: Prisma.RepuestoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repuesto
   */
  omit?: Prisma.RepuestoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoInclude<ExtArgs> | null
}
