
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RepuestoMantenimiento` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RepuestoMantenimiento
 * 
 */
export type RepuestoMantenimientoModel = runtime.Types.Result.DefaultSelection<Prisma.$RepuestoMantenimientoPayload>

export type AggregateRepuestoMantenimiento = {
  _count: RepuestoMantenimientoCountAggregateOutputType | null
  _avg: RepuestoMantenimientoAvgAggregateOutputType | null
  _sum: RepuestoMantenimientoSumAggregateOutputType | null
  _min: RepuestoMantenimientoMinAggregateOutputType | null
  _max: RepuestoMantenimientoMaxAggregateOutputType | null
}

export type RepuestoMantenimientoAvgAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
}

export type RepuestoMantenimientoSumAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
}

export type RepuestoMantenimientoMinAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type RepuestoMantenimientoMaxAggregateOutputType = {
  id: number | null
  mantenimientoId: number | null
  repuestoId: number | null
  cantidad: number | null
  costoUnitario: runtime.Decimal | null
  creadoEn: Date | null
}

export type RepuestoMantenimientoCountAggregateOutputType = {
  id: number
  mantenimientoId: number
  repuestoId: number
  cantidad: number
  costoUnitario: number
  creadoEn: number
  _all: number
}


export type RepuestoMantenimientoAvgAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
}

export type RepuestoMantenimientoSumAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
}

export type RepuestoMantenimientoMinAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
}

export type RepuestoMantenimientoMaxAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
}

export type RepuestoMantenimientoCountAggregateInputType = {
  id?: true
  mantenimientoId?: true
  repuestoId?: true
  cantidad?: true
  costoUnitario?: true
  creadoEn?: true
  _all?: true
}

export type RepuestoMantenimientoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RepuestoMantenimiento to aggregate.
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RepuestoMantenimientos to fetch.
   */
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RepuestoMantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RepuestoMantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RepuestoMantenimientos
  **/
  _count?: true | RepuestoMantenimientoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RepuestoMantenimientoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RepuestoMantenimientoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RepuestoMantenimientoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RepuestoMantenimientoMaxAggregateInputType
}

export type GetRepuestoMantenimientoAggregateType<T extends RepuestoMantenimientoAggregateArgs> = {
      [P in keyof T & keyof AggregateRepuestoMantenimiento]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRepuestoMantenimiento[P]>
    : Prisma.GetScalarType<T[P], AggregateRepuestoMantenimiento[P]>
}




export type RepuestoMantenimientoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RepuestoMantenimientoWhereInput
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithAggregationInput | Prisma.RepuestoMantenimientoOrderByWithAggregationInput[]
  by: Prisma.RepuestoMantenimientoScalarFieldEnum[] | Prisma.RepuestoMantenimientoScalarFieldEnum
  having?: Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RepuestoMantenimientoCountAggregateInputType | true
  _avg?: RepuestoMantenimientoAvgAggregateInputType
  _sum?: RepuestoMantenimientoSumAggregateInputType
  _min?: RepuestoMantenimientoMinAggregateInputType
  _max?: RepuestoMantenimientoMaxAggregateInputType
}

export type RepuestoMantenimientoGroupByOutputType = {
  id: number
  mantenimientoId: number
  repuestoId: number
  cantidad: number
  costoUnitario: runtime.Decimal
  creadoEn: Date
  _count: RepuestoMantenimientoCountAggregateOutputType | null
  _avg: RepuestoMantenimientoAvgAggregateOutputType | null
  _sum: RepuestoMantenimientoSumAggregateOutputType | null
  _min: RepuestoMantenimientoMinAggregateOutputType | null
  _max: RepuestoMantenimientoMaxAggregateOutputType | null
}

export type GetRepuestoMantenimientoGroupByPayload<T extends RepuestoMantenimientoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RepuestoMantenimientoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RepuestoMantenimientoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RepuestoMantenimientoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RepuestoMantenimientoGroupByOutputType[P]>
      }
    >
  >



export type RepuestoMantenimientoWhereInput = {
  AND?: Prisma.RepuestoMantenimientoWhereInput | Prisma.RepuestoMantenimientoWhereInput[]
  OR?: Prisma.RepuestoMantenimientoWhereInput[]
  NOT?: Prisma.RepuestoMantenimientoWhereInput | Prisma.RepuestoMantenimientoWhereInput[]
  id?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  mantenimientoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  repuestoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  cantidad?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  costoUnitario?: Prisma.DecimalFilter<"RepuestoMantenimiento"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"RepuestoMantenimiento"> | Date | string
  mantenimiento?: Prisma.XOR<Prisma.MantenimientoScalarRelationFilter, Prisma.MantenimientoWhereInput>
  repuesto?: Prisma.XOR<Prisma.RepuestoScalarRelationFilter, Prisma.RepuestoWhereInput>
}

export type RepuestoMantenimientoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  mantenimiento?: Prisma.MantenimientoOrderByWithRelationInput
  repuesto?: Prisma.RepuestoOrderByWithRelationInput
}

export type RepuestoMantenimientoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.RepuestoMantenimientoWhereInput | Prisma.RepuestoMantenimientoWhereInput[]
  OR?: Prisma.RepuestoMantenimientoWhereInput[]
  NOT?: Prisma.RepuestoMantenimientoWhereInput | Prisma.RepuestoMantenimientoWhereInput[]
  mantenimientoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  repuestoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  cantidad?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  costoUnitario?: Prisma.DecimalFilter<"RepuestoMantenimiento"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"RepuestoMantenimiento"> | Date | string
  mantenimiento?: Prisma.XOR<Prisma.MantenimientoScalarRelationFilter, Prisma.MantenimientoWhereInput>
  repuesto?: Prisma.XOR<Prisma.RepuestoScalarRelationFilter, Prisma.RepuestoWhereInput>
}, "id">

export type RepuestoMantenimientoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  _count?: Prisma.RepuestoMantenimientoCountOrderByAggregateInput
  _avg?: Prisma.RepuestoMantenimientoAvgOrderByAggregateInput
  _max?: Prisma.RepuestoMantenimientoMaxOrderByAggregateInput
  _min?: Prisma.RepuestoMantenimientoMinOrderByAggregateInput
  _sum?: Prisma.RepuestoMantenimientoSumOrderByAggregateInput
}

export type RepuestoMantenimientoScalarWhereWithAggregatesInput = {
  AND?: Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput | Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput[]
  OR?: Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput | Prisma.RepuestoMantenimientoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"RepuestoMantenimiento"> | number
  mantenimientoId?: Prisma.IntWithAggregatesFilter<"RepuestoMantenimiento"> | number
  repuestoId?: Prisma.IntWithAggregatesFilter<"RepuestoMantenimiento"> | number
  cantidad?: Prisma.IntWithAggregatesFilter<"RepuestoMantenimiento"> | number
  costoUnitario?: Prisma.DecimalWithAggregatesFilter<"RepuestoMantenimiento"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeWithAggregatesFilter<"RepuestoMantenimiento"> | Date | string
}

export type RepuestoMantenimientoCreateInput = {
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimiento: Prisma.MantenimientoCreateNestedOneWithoutRepuestosInput
  repuesto: Prisma.RepuestoCreateNestedOneWithoutMantenimientosInput
}

export type RepuestoMantenimientoUncheckedCreateInput = {
  id?: number
  mantenimientoId: number
  repuestoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoUpdateInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimiento?: Prisma.MantenimientoUpdateOneRequiredWithoutRepuestosNestedInput
  repuesto?: Prisma.RepuestoUpdateOneRequiredWithoutMantenimientosNestedInput
}

export type RepuestoMantenimientoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoCreateManyInput = {
  id?: number
  mantenimientoId: number
  repuestoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoUpdateManyMutationInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoListRelationFilter = {
  every?: Prisma.RepuestoMantenimientoWhereInput
  some?: Prisma.RepuestoMantenimientoWhereInput
  none?: Prisma.RepuestoMantenimientoWhereInput
}

export type RepuestoMantenimientoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RepuestoMantenimientoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoMantenimientoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
}

export type RepuestoMantenimientoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoMantenimientoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type RepuestoMantenimientoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mantenimientoId?: Prisma.SortOrder
  repuestoId?: Prisma.SortOrder
  cantidad?: Prisma.SortOrder
  costoUnitario?: Prisma.SortOrder
}

export type RepuestoMantenimientoCreateNestedManyWithoutMantenimientoInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput> | Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyMantenimientoInputEnvelope
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
}

export type RepuestoMantenimientoUncheckedCreateNestedManyWithoutMantenimientoInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput> | Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyMantenimientoInputEnvelope
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
}

export type RepuestoMantenimientoUpdateManyWithoutMantenimientoNestedInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput> | Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput[]
  upsert?: Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutMantenimientoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyMantenimientoInputEnvelope
  set?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  disconnect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  delete?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  update?: Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutMantenimientoInput[]
  updateMany?: Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutMantenimientoInput[]
  deleteMany?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
}

export type RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoNestedInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput> | Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput[]
  upsert?: Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutMantenimientoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyMantenimientoInputEnvelope
  set?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  disconnect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  delete?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  update?: Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutMantenimientoInput[]
  updateMany?: Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutMantenimientoInput | Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutMantenimientoInput[]
  deleteMany?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
}

export type RepuestoMantenimientoCreateNestedManyWithoutRepuestoInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput> | Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyRepuestoInputEnvelope
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
}

export type RepuestoMantenimientoUncheckedCreateNestedManyWithoutRepuestoInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput> | Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyRepuestoInputEnvelope
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
}

export type RepuestoMantenimientoUpdateManyWithoutRepuestoNestedInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput> | Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput[]
  upsert?: Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutRepuestoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyRepuestoInputEnvelope
  set?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  disconnect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  delete?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  update?: Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutRepuestoInput[]
  updateMany?: Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutRepuestoInput[]
  deleteMany?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
}

export type RepuestoMantenimientoUncheckedUpdateManyWithoutRepuestoNestedInput = {
  create?: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput> | Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput[] | Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput[]
  connectOrCreate?: Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput | Prisma.RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput[]
  upsert?: Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpsertWithWhereUniqueWithoutRepuestoInput[]
  createMany?: Prisma.RepuestoMantenimientoCreateManyRepuestoInputEnvelope
  set?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  disconnect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  delete?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  connect?: Prisma.RepuestoMantenimientoWhereUniqueInput | Prisma.RepuestoMantenimientoWhereUniqueInput[]
  update?: Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpdateWithWhereUniqueWithoutRepuestoInput[]
  updateMany?: Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutRepuestoInput | Prisma.RepuestoMantenimientoUpdateManyWithWhereWithoutRepuestoInput[]
  deleteMany?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
}

export type RepuestoMantenimientoCreateWithoutMantenimientoInput = {
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  repuesto: Prisma.RepuestoCreateNestedOneWithoutMantenimientosInput
}

export type RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput = {
  id?: number
  repuestoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoCreateOrConnectWithoutMantenimientoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  create: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput>
}

export type RepuestoMantenimientoCreateManyMantenimientoInputEnvelope = {
  data: Prisma.RepuestoMantenimientoCreateManyMantenimientoInput | Prisma.RepuestoMantenimientoCreateManyMantenimientoInput[]
  skipDuplicates?: boolean
}

export type RepuestoMantenimientoUpsertWithWhereUniqueWithoutMantenimientoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  update: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedUpdateWithoutMantenimientoInput>
  create: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutMantenimientoInput>
}

export type RepuestoMantenimientoUpdateWithWhereUniqueWithoutMantenimientoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateWithoutMantenimientoInput, Prisma.RepuestoMantenimientoUncheckedUpdateWithoutMantenimientoInput>
}

export type RepuestoMantenimientoUpdateManyWithWhereWithoutMantenimientoInput = {
  where: Prisma.RepuestoMantenimientoScalarWhereInput
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateManyMutationInput, Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoInput>
}

export type RepuestoMantenimientoScalarWhereInput = {
  AND?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
  OR?: Prisma.RepuestoMantenimientoScalarWhereInput[]
  NOT?: Prisma.RepuestoMantenimientoScalarWhereInput | Prisma.RepuestoMantenimientoScalarWhereInput[]
  id?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  mantenimientoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  repuestoId?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  cantidad?: Prisma.IntFilter<"RepuestoMantenimiento"> | number
  costoUnitario?: Prisma.DecimalFilter<"RepuestoMantenimiento"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFilter<"RepuestoMantenimiento"> | Date | string
}

export type RepuestoMantenimientoCreateWithoutRepuestoInput = {
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
  mantenimiento: Prisma.MantenimientoCreateNestedOneWithoutRepuestosInput
}

export type RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput = {
  id?: number
  mantenimientoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoCreateOrConnectWithoutRepuestoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  create: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput>
}

export type RepuestoMantenimientoCreateManyRepuestoInputEnvelope = {
  data: Prisma.RepuestoMantenimientoCreateManyRepuestoInput | Prisma.RepuestoMantenimientoCreateManyRepuestoInput[]
  skipDuplicates?: boolean
}

export type RepuestoMantenimientoUpsertWithWhereUniqueWithoutRepuestoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  update: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedUpdateWithoutRepuestoInput>
  create: Prisma.XOR<Prisma.RepuestoMantenimientoCreateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedCreateWithoutRepuestoInput>
}

export type RepuestoMantenimientoUpdateWithWhereUniqueWithoutRepuestoInput = {
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateWithoutRepuestoInput, Prisma.RepuestoMantenimientoUncheckedUpdateWithoutRepuestoInput>
}

export type RepuestoMantenimientoUpdateManyWithWhereWithoutRepuestoInput = {
  where: Prisma.RepuestoMantenimientoScalarWhereInput
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateManyMutationInput, Prisma.RepuestoMantenimientoUncheckedUpdateManyWithoutRepuestoInput>
}

export type RepuestoMantenimientoCreateManyMantenimientoInput = {
  id?: number
  repuestoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoUpdateWithoutMantenimientoInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repuesto?: Prisma.RepuestoUpdateOneRequiredWithoutMantenimientosNestedInput
}

export type RepuestoMantenimientoUncheckedUpdateWithoutMantenimientoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoUncheckedUpdateManyWithoutMantenimientoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  repuestoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoCreateManyRepuestoInput = {
  id?: number
  mantenimientoId: number
  cantidad?: number
  costoUnitario?: runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Date | string
}

export type RepuestoMantenimientoUpdateWithoutRepuestoInput = {
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimiento?: Prisma.MantenimientoUpdateOneRequiredWithoutRepuestosNestedInput
}

export type RepuestoMantenimientoUncheckedUpdateWithoutRepuestoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RepuestoMantenimientoUncheckedUpdateManyWithoutRepuestoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mantenimientoId?: Prisma.IntFieldUpdateOperationsInput | number
  cantidad?: Prisma.IntFieldUpdateOperationsInput | number
  costoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RepuestoMantenimientoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mantenimientoId?: boolean
  repuestoId?: boolean
  cantidad?: boolean
  costoUnitario?: boolean
  creadoEn?: boolean
  mantenimiento?: boolean | Prisma.MantenimientoDefaultArgs<ExtArgs>
  repuesto?: boolean | Prisma.RepuestoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["repuestoMantenimiento"]>



export type RepuestoMantenimientoSelectScalar = {
  id?: boolean
  mantenimientoId?: boolean
  repuestoId?: boolean
  cantidad?: boolean
  costoUnitario?: boolean
  creadoEn?: boolean
}

export type RepuestoMantenimientoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mantenimientoId" | "repuestoId" | "cantidad" | "costoUnitario" | "creadoEn", ExtArgs["result"]["repuestoMantenimiento"]>
export type RepuestoMantenimientoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mantenimiento?: boolean | Prisma.MantenimientoDefaultArgs<ExtArgs>
  repuesto?: boolean | Prisma.RepuestoDefaultArgs<ExtArgs>
}

export type $RepuestoMantenimientoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RepuestoMantenimiento"
  objects: {
    mantenimiento: Prisma.$MantenimientoPayload<ExtArgs>
    repuesto: Prisma.$RepuestoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    mantenimientoId: number
    repuestoId: number
    cantidad: number
    costoUnitario: runtime.Decimal
    creadoEn: Date
  }, ExtArgs["result"]["repuestoMantenimiento"]>
  composites: {}
}

export type RepuestoMantenimientoGetPayload<S extends boolean | null | undefined | RepuestoMantenimientoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload, S>

export type RepuestoMantenimientoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RepuestoMantenimientoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RepuestoMantenimientoCountAggregateInputType | true
  }

export interface RepuestoMantenimientoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RepuestoMantenimiento'], meta: { name: 'RepuestoMantenimiento' } }
  /**
   * Find zero or one RepuestoMantenimiento that matches the filter.
   * @param {RepuestoMantenimientoFindUniqueArgs} args - Arguments to find a RepuestoMantenimiento
   * @example
   * // Get one RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RepuestoMantenimientoFindUniqueArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RepuestoMantenimiento that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RepuestoMantenimientoFindUniqueOrThrowArgs} args - Arguments to find a RepuestoMantenimiento
   * @example
   * // Get one RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RepuestoMantenimientoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RepuestoMantenimiento that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoFindFirstArgs} args - Arguments to find a RepuestoMantenimiento
   * @example
   * // Get one RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RepuestoMantenimientoFindFirstArgs>(args?: Prisma.SelectSubset<T, RepuestoMantenimientoFindFirstArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RepuestoMantenimiento that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoFindFirstOrThrowArgs} args - Arguments to find a RepuestoMantenimiento
   * @example
   * // Get one RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RepuestoMantenimientoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RepuestoMantenimientoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RepuestoMantenimientos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RepuestoMantenimientos
   * const repuestoMantenimientos = await prisma.repuestoMantenimiento.findMany()
   * 
   * // Get first 10 RepuestoMantenimientos
   * const repuestoMantenimientos = await prisma.repuestoMantenimiento.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const repuestoMantenimientoWithIdOnly = await prisma.repuestoMantenimiento.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RepuestoMantenimientoFindManyArgs>(args?: Prisma.SelectSubset<T, RepuestoMantenimientoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RepuestoMantenimiento.
   * @param {RepuestoMantenimientoCreateArgs} args - Arguments to create a RepuestoMantenimiento.
   * @example
   * // Create one RepuestoMantenimiento
   * const RepuestoMantenimiento = await prisma.repuestoMantenimiento.create({
   *   data: {
   *     // ... data to create a RepuestoMantenimiento
   *   }
   * })
   * 
   */
  create<T extends RepuestoMantenimientoCreateArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoCreateArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RepuestoMantenimientos.
   * @param {RepuestoMantenimientoCreateManyArgs} args - Arguments to create many RepuestoMantenimientos.
   * @example
   * // Create many RepuestoMantenimientos
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RepuestoMantenimientoCreateManyArgs>(args?: Prisma.SelectSubset<T, RepuestoMantenimientoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a RepuestoMantenimiento.
   * @param {RepuestoMantenimientoDeleteArgs} args - Arguments to delete one RepuestoMantenimiento.
   * @example
   * // Delete one RepuestoMantenimiento
   * const RepuestoMantenimiento = await prisma.repuestoMantenimiento.delete({
   *   where: {
   *     // ... filter to delete one RepuestoMantenimiento
   *   }
   * })
   * 
   */
  delete<T extends RepuestoMantenimientoDeleteArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoDeleteArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RepuestoMantenimiento.
   * @param {RepuestoMantenimientoUpdateArgs} args - Arguments to update one RepuestoMantenimiento.
   * @example
   * // Update one RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RepuestoMantenimientoUpdateArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoUpdateArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RepuestoMantenimientos.
   * @param {RepuestoMantenimientoDeleteManyArgs} args - Arguments to filter RepuestoMantenimientos to delete.
   * @example
   * // Delete a few RepuestoMantenimientos
   * const { count } = await prisma.repuestoMantenimiento.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RepuestoMantenimientoDeleteManyArgs>(args?: Prisma.SelectSubset<T, RepuestoMantenimientoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RepuestoMantenimientos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RepuestoMantenimientos
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RepuestoMantenimientoUpdateManyArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one RepuestoMantenimiento.
   * @param {RepuestoMantenimientoUpsertArgs} args - Arguments to update or create a RepuestoMantenimiento.
   * @example
   * // Update or create a RepuestoMantenimiento
   * const repuestoMantenimiento = await prisma.repuestoMantenimiento.upsert({
   *   create: {
   *     // ... data to create a RepuestoMantenimiento
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RepuestoMantenimiento we want to update
   *   }
   * })
   */
  upsert<T extends RepuestoMantenimientoUpsertArgs>(args: Prisma.SelectSubset<T, RepuestoMantenimientoUpsertArgs<ExtArgs>>): Prisma.Prisma__RepuestoMantenimientoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoMantenimientoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RepuestoMantenimientos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoCountArgs} args - Arguments to filter RepuestoMantenimientos to count.
   * @example
   * // Count the number of RepuestoMantenimientos
   * const count = await prisma.repuestoMantenimiento.count({
   *   where: {
   *     // ... the filter for the RepuestoMantenimientos we want to count
   *   }
   * })
  **/
  count<T extends RepuestoMantenimientoCountArgs>(
    args?: Prisma.Subset<T, RepuestoMantenimientoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RepuestoMantenimientoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RepuestoMantenimiento.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RepuestoMantenimientoAggregateArgs>(args: Prisma.Subset<T, RepuestoMantenimientoAggregateArgs>): Prisma.PrismaPromise<GetRepuestoMantenimientoAggregateType<T>>

  /**
   * Group by RepuestoMantenimiento.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RepuestoMantenimientoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RepuestoMantenimientoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RepuestoMantenimientoGroupByArgs['orderBy'] }
      : { orderBy?: RepuestoMantenimientoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RepuestoMantenimientoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRepuestoMantenimientoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RepuestoMantenimiento model
 */
readonly fields: RepuestoMantenimientoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RepuestoMantenimiento.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RepuestoMantenimientoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mantenimiento<T extends Prisma.MantenimientoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MantenimientoDefaultArgs<ExtArgs>>): Prisma.Prisma__MantenimientoClient<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  repuesto<T extends Prisma.RepuestoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RepuestoDefaultArgs<ExtArgs>>): Prisma.Prisma__RepuestoClient<runtime.Types.Result.GetResult<Prisma.$RepuestoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RepuestoMantenimiento model
 */
export interface RepuestoMantenimientoFieldRefs {
  readonly id: Prisma.FieldRef<"RepuestoMantenimiento", 'Int'>
  readonly mantenimientoId: Prisma.FieldRef<"RepuestoMantenimiento", 'Int'>
  readonly repuestoId: Prisma.FieldRef<"RepuestoMantenimiento", 'Int'>
  readonly cantidad: Prisma.FieldRef<"RepuestoMantenimiento", 'Int'>
  readonly costoUnitario: Prisma.FieldRef<"RepuestoMantenimiento", 'Decimal'>
  readonly creadoEn: Prisma.FieldRef<"RepuestoMantenimiento", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RepuestoMantenimiento findUnique
 */
export type RepuestoMantenimientoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which RepuestoMantenimiento to fetch.
   */
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
}

/**
 * RepuestoMantenimiento findUniqueOrThrow
 */
export type RepuestoMantenimientoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which RepuestoMantenimiento to fetch.
   */
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
}

/**
 * RepuestoMantenimiento findFirst
 */
export type RepuestoMantenimientoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which RepuestoMantenimiento to fetch.
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RepuestoMantenimientos to fetch.
   */
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RepuestoMantenimientos.
   */
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RepuestoMantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RepuestoMantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RepuestoMantenimientos.
   */
  distinct?: Prisma.RepuestoMantenimientoScalarFieldEnum | Prisma.RepuestoMantenimientoScalarFieldEnum[]
}

/**
 * RepuestoMantenimiento findFirstOrThrow
 */
export type RepuestoMantenimientoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which RepuestoMantenimiento to fetch.
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RepuestoMantenimientos to fetch.
   */
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RepuestoMantenimientos.
   */
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RepuestoMantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RepuestoMantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RepuestoMantenimientos.
   */
  distinct?: Prisma.RepuestoMantenimientoScalarFieldEnum | Prisma.RepuestoMantenimientoScalarFieldEnum[]
}

/**
 * RepuestoMantenimiento findMany
 */
export type RepuestoMantenimientoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter, which RepuestoMantenimientos to fetch.
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RepuestoMantenimientos to fetch.
   */
  orderBy?: Prisma.RepuestoMantenimientoOrderByWithRelationInput | Prisma.RepuestoMantenimientoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RepuestoMantenimientos.
   */
  cursor?: Prisma.RepuestoMantenimientoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RepuestoMantenimientos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RepuestoMantenimientos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RepuestoMantenimientos.
   */
  distinct?: Prisma.RepuestoMantenimientoScalarFieldEnum | Prisma.RepuestoMantenimientoScalarFieldEnum[]
}

/**
 * RepuestoMantenimiento create
 */
export type RepuestoMantenimientoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * The data needed to create a RepuestoMantenimiento.
   */
  data: Prisma.XOR<Prisma.RepuestoMantenimientoCreateInput, Prisma.RepuestoMantenimientoUncheckedCreateInput>
}

/**
 * RepuestoMantenimiento createMany
 */
export type RepuestoMantenimientoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RepuestoMantenimientos.
   */
  data: Prisma.RepuestoMantenimientoCreateManyInput | Prisma.RepuestoMantenimientoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RepuestoMantenimiento update
 */
export type RepuestoMantenimientoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * The data needed to update a RepuestoMantenimiento.
   */
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateInput, Prisma.RepuestoMantenimientoUncheckedUpdateInput>
  /**
   * Choose, which RepuestoMantenimiento to update.
   */
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
}

/**
 * RepuestoMantenimiento updateMany
 */
export type RepuestoMantenimientoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RepuestoMantenimientos.
   */
  data: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateManyMutationInput, Prisma.RepuestoMantenimientoUncheckedUpdateManyInput>
  /**
   * Filter which RepuestoMantenimientos to update
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * Limit how many RepuestoMantenimientos to update.
   */
  limit?: number
}

/**
 * RepuestoMantenimiento upsert
 */
export type RepuestoMantenimientoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * The filter to search for the RepuestoMantenimiento to update in case it exists.
   */
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
  /**
   * In case the RepuestoMantenimiento found by the `where` argument doesn't exist, create a new RepuestoMantenimiento with this data.
   */
  create: Prisma.XOR<Prisma.RepuestoMantenimientoCreateInput, Prisma.RepuestoMantenimientoUncheckedCreateInput>
  /**
   * In case the RepuestoMantenimiento was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RepuestoMantenimientoUpdateInput, Prisma.RepuestoMantenimientoUncheckedUpdateInput>
}

/**
 * RepuestoMantenimiento delete
 */
export type RepuestoMantenimientoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
  /**
   * Filter which RepuestoMantenimiento to delete.
   */
  where: Prisma.RepuestoMantenimientoWhereUniqueInput
}

/**
 * RepuestoMantenimiento deleteMany
 */
export type RepuestoMantenimientoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RepuestoMantenimientos to delete
   */
  where?: Prisma.RepuestoMantenimientoWhereInput
  /**
   * Limit how many RepuestoMantenimientos to delete.
   */
  limit?: number
}

/**
 * RepuestoMantenimiento without action
 */
export type RepuestoMantenimientoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RepuestoMantenimiento
   */
  select?: Prisma.RepuestoMantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RepuestoMantenimiento
   */
  omit?: Prisma.RepuestoMantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepuestoMantenimientoInclude<ExtArgs> | null
}
