
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tickets` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model tickets
 * 
 */
export type ticketsModel = runtime.Types.Result.DefaultSelection<Prisma.$ticketsPayload>

export type AggregateTickets = {
  _count: TicketsCountAggregateOutputType | null
  _avg: TicketsAvgAggregateOutputType | null
  _sum: TicketsSumAggregateOutputType | null
  _min: TicketsMinAggregateOutputType | null
  _max: TicketsMaxAggregateOutputType | null
}

export type TicketsAvgAggregateOutputType = {
  id: number | null
  equipo_id: number | null
  solicitante_id: number | null
  tecnico_id: number | null
}

export type TicketsSumAggregateOutputType = {
  id: number | null
  equipo_id: number | null
  solicitante_id: number | null
  tecnico_id: number | null
}

export type TicketsMinAggregateOutputType = {
  id: number | null
  titulo: string | null
  descripcion: string | null
  prioridad: string | null
  estado: string | null
  equipo_id: number | null
  solicitante_id: number | null
  tecnico_id: number | null
  fecha_cierre: Date | null
  creado_en: Date | null
  actualizado_en: Date | null
}

export type TicketsMaxAggregateOutputType = {
  id: number | null
  titulo: string | null
  descripcion: string | null
  prioridad: string | null
  estado: string | null
  equipo_id: number | null
  solicitante_id: number | null
  tecnico_id: number | null
  fecha_cierre: Date | null
  creado_en: Date | null
  actualizado_en: Date | null
}

export type TicketsCountAggregateOutputType = {
  id: number
  titulo: number
  descripcion: number
  prioridad: number
  estado: number
  equipo_id: number
  solicitante_id: number
  tecnico_id: number
  fecha_cierre: number
  creado_en: number
  actualizado_en: number
  _all: number
}


export type TicketsAvgAggregateInputType = {
  id?: true
  equipo_id?: true
  solicitante_id?: true
  tecnico_id?: true
}

export type TicketsSumAggregateInputType = {
  id?: true
  equipo_id?: true
  solicitante_id?: true
  tecnico_id?: true
}

export type TicketsMinAggregateInputType = {
  id?: true
  titulo?: true
  descripcion?: true
  prioridad?: true
  estado?: true
  equipo_id?: true
  solicitante_id?: true
  tecnico_id?: true
  fecha_cierre?: true
  creado_en?: true
  actualizado_en?: true
}

export type TicketsMaxAggregateInputType = {
  id?: true
  titulo?: true
  descripcion?: true
  prioridad?: true
  estado?: true
  equipo_id?: true
  solicitante_id?: true
  tecnico_id?: true
  fecha_cierre?: true
  creado_en?: true
  actualizado_en?: true
}

export type TicketsCountAggregateInputType = {
  id?: true
  titulo?: true
  descripcion?: true
  prioridad?: true
  estado?: true
  equipo_id?: true
  solicitante_id?: true
  tecnico_id?: true
  fecha_cierre?: true
  creado_en?: true
  actualizado_en?: true
  _all?: true
}

export type TicketsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tickets to aggregate.
   */
  where?: Prisma.ticketsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketsOrderByWithRelationInput | Prisma.ticketsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ticketsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tickets
  **/
  _count?: true | TicketsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketsMaxAggregateInputType
}

export type GetTicketsAggregateType<T extends TicketsAggregateArgs> = {
      [P in keyof T & keyof AggregateTickets]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTickets[P]>
    : Prisma.GetScalarType<T[P], AggregateTickets[P]>
}




export type ticketsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ticketsWhereInput
  orderBy?: Prisma.ticketsOrderByWithAggregationInput | Prisma.ticketsOrderByWithAggregationInput[]
  by: Prisma.TicketsScalarFieldEnum[] | Prisma.TicketsScalarFieldEnum
  having?: Prisma.ticketsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketsCountAggregateInputType | true
  _avg?: TicketsAvgAggregateInputType
  _sum?: TicketsSumAggregateInputType
  _min?: TicketsMinAggregateInputType
  _max?: TicketsMaxAggregateInputType
}

export type TicketsGroupByOutputType = {
  id: number
  titulo: string
  descripcion: string
  prioridad: string
  estado: string
  equipo_id: number
  solicitante_id: number
  tecnico_id: number | null
  fecha_cierre: Date | null
  creado_en: Date
  actualizado_en: Date
  _count: TicketsCountAggregateOutputType | null
  _avg: TicketsAvgAggregateOutputType | null
  _sum: TicketsSumAggregateOutputType | null
  _min: TicketsMinAggregateOutputType | null
  _max: TicketsMaxAggregateOutputType | null
}

export type GetTicketsGroupByPayload<T extends ticketsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketsGroupByOutputType[P]>
      }
    >
  >



export type ticketsWhereInput = {
  AND?: Prisma.ticketsWhereInput | Prisma.ticketsWhereInput[]
  OR?: Prisma.ticketsWhereInput[]
  NOT?: Prisma.ticketsWhereInput | Prisma.ticketsWhereInput[]
  id?: Prisma.IntFilter<"tickets"> | number
  titulo?: Prisma.StringFilter<"tickets"> | string
  descripcion?: Prisma.StringFilter<"tickets"> | string
  prioridad?: Prisma.StringFilter<"tickets"> | string
  estado?: Prisma.StringFilter<"tickets"> | string
  equipo_id?: Prisma.IntFilter<"tickets"> | number
  solicitante_id?: Prisma.IntFilter<"tickets"> | number
  tecnico_id?: Prisma.IntNullableFilter<"tickets"> | number | null
  fecha_cierre?: Prisma.DateTimeNullableFilter<"tickets"> | Date | string | null
  creado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
  actualizado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
  equipos?: Prisma.XOR<Prisma.EquipoScalarRelationFilter, Prisma.EquipoWhereInput>
  usuarios_tickets_solicitante_idTousuarios?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  usuarios_tickets_tecnico_idTousuarios?: Prisma.XOR<Prisma.UsuarioNullableScalarRelationFilter, Prisma.UsuarioWhereInput> | null
  mantenimientos?: Prisma.MantenimientoListRelationFilter
}

export type ticketsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  prioridad?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha_cierre?: Prisma.SortOrderInput | Prisma.SortOrder
  creado_en?: Prisma.SortOrder
  actualizado_en?: Prisma.SortOrder
  equipos?: Prisma.EquipoOrderByWithRelationInput
  usuarios_tickets_solicitante_idTousuarios?: Prisma.UsuarioOrderByWithRelationInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioOrderByWithRelationInput
  mantenimientos?: Prisma.MantenimientoOrderByRelationAggregateInput
  _relevance?: Prisma.ticketsOrderByRelevanceInput
}

export type ticketsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ticketsWhereInput | Prisma.ticketsWhereInput[]
  OR?: Prisma.ticketsWhereInput[]
  NOT?: Prisma.ticketsWhereInput | Prisma.ticketsWhereInput[]
  titulo?: Prisma.StringFilter<"tickets"> | string
  descripcion?: Prisma.StringFilter<"tickets"> | string
  prioridad?: Prisma.StringFilter<"tickets"> | string
  estado?: Prisma.StringFilter<"tickets"> | string
  equipo_id?: Prisma.IntFilter<"tickets"> | number
  solicitante_id?: Prisma.IntFilter<"tickets"> | number
  tecnico_id?: Prisma.IntNullableFilter<"tickets"> | number | null
  fecha_cierre?: Prisma.DateTimeNullableFilter<"tickets"> | Date | string | null
  creado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
  actualizado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
  equipos?: Prisma.XOR<Prisma.EquipoScalarRelationFilter, Prisma.EquipoWhereInput>
  usuarios_tickets_solicitante_idTousuarios?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  usuarios_tickets_tecnico_idTousuarios?: Prisma.XOR<Prisma.UsuarioNullableScalarRelationFilter, Prisma.UsuarioWhereInput> | null
  mantenimientos?: Prisma.MantenimientoListRelationFilter
}, "id">

export type ticketsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  prioridad?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha_cierre?: Prisma.SortOrderInput | Prisma.SortOrder
  creado_en?: Prisma.SortOrder
  actualizado_en?: Prisma.SortOrder
  _count?: Prisma.ticketsCountOrderByAggregateInput
  _avg?: Prisma.ticketsAvgOrderByAggregateInput
  _max?: Prisma.ticketsMaxOrderByAggregateInput
  _min?: Prisma.ticketsMinOrderByAggregateInput
  _sum?: Prisma.ticketsSumOrderByAggregateInput
}

export type ticketsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ticketsScalarWhereWithAggregatesInput | Prisma.ticketsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ticketsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ticketsScalarWhereWithAggregatesInput | Prisma.ticketsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"tickets"> | number
  titulo?: Prisma.StringWithAggregatesFilter<"tickets"> | string
  descripcion?: Prisma.StringWithAggregatesFilter<"tickets"> | string
  prioridad?: Prisma.StringWithAggregatesFilter<"tickets"> | string
  estado?: Prisma.StringWithAggregatesFilter<"tickets"> | string
  equipo_id?: Prisma.IntWithAggregatesFilter<"tickets"> | number
  solicitante_id?: Prisma.IntWithAggregatesFilter<"tickets"> | number
  tecnico_id?: Prisma.IntNullableWithAggregatesFilter<"tickets"> | number | null
  fecha_cierre?: Prisma.DateTimeNullableWithAggregatesFilter<"tickets"> | Date | string | null
  creado_en?: Prisma.DateTimeWithAggregatesFilter<"tickets"> | Date | string
  actualizado_en?: Prisma.DateTimeWithAggregatesFilter<"tickets"> | Date | string
}

export type ticketsCreateInput = {
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  equipos: Prisma.EquipoCreateNestedOneWithoutTicketsInput
  usuarios_tickets_solicitante_idTousuarios: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_solicitante_idTousuariosInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_tecnico_idTousuariosInput
  mantenimientos?: Prisma.MantenimientoCreateNestedManyWithoutTicketInput
}

export type ticketsUncheckedCreateInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  solicitante_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketsUpdateInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipos?: Prisma.EquipoUpdateOneRequiredWithoutTicketsNestedInput
  usuarios_tickets_solicitante_idTousuarios?: Prisma.UsuarioUpdateOneRequiredWithoutTickets_tickets_solicitante_idTousuariosNestedInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioUpdateOneWithoutTickets_tickets_tecnico_idTousuariosNestedInput
  mantenimientos?: Prisma.MantenimientoUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketsCreateManyInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  solicitante_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
}

export type ticketsUpdateManyMutationInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ticketsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketsListRelationFilter = {
  every?: Prisma.ticketsWhereInput
  some?: Prisma.ticketsWhereInput
  none?: Prisma.ticketsWhereInput
}

export type ticketsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketsNullableScalarRelationFilter = {
  is?: Prisma.ticketsWhereInput | null
  isNot?: Prisma.ticketsWhereInput | null
}

export type ticketsOrderByRelevanceInput = {
  fields: Prisma.ticketsOrderByRelevanceFieldEnum | Prisma.ticketsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ticketsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  prioridad?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrder
  fecha_cierre?: Prisma.SortOrder
  creado_en?: Prisma.SortOrder
  actualizado_en?: Prisma.SortOrder
}

export type ticketsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrder
}

export type ticketsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  prioridad?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrder
  fecha_cierre?: Prisma.SortOrder
  creado_en?: Prisma.SortOrder
  actualizado_en?: Prisma.SortOrder
}

export type ticketsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  prioridad?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrder
  fecha_cierre?: Prisma.SortOrder
  creado_en?: Prisma.SortOrder
  actualizado_en?: Prisma.SortOrder
}

export type ticketsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  equipo_id?: Prisma.SortOrder
  solicitante_id?: Prisma.SortOrder
  tecnico_id?: Prisma.SortOrder
}

export type ticketsCreateNestedManyWithoutEquiposInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput> | Prisma.ticketsCreateWithoutEquiposInput[] | Prisma.ticketsUncheckedCreateWithoutEquiposInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutEquiposInput | Prisma.ticketsCreateOrConnectWithoutEquiposInput[]
  createMany?: Prisma.ticketsCreateManyEquiposInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsUncheckedCreateNestedManyWithoutEquiposInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput> | Prisma.ticketsCreateWithoutEquiposInput[] | Prisma.ticketsUncheckedCreateWithoutEquiposInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutEquiposInput | Prisma.ticketsCreateOrConnectWithoutEquiposInput[]
  createMany?: Prisma.ticketsCreateManyEquiposInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsUpdateManyWithoutEquiposNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput> | Prisma.ticketsCreateWithoutEquiposInput[] | Prisma.ticketsUncheckedCreateWithoutEquiposInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutEquiposInput | Prisma.ticketsCreateOrConnectWithoutEquiposInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutEquiposInput | Prisma.ticketsUpsertWithWhereUniqueWithoutEquiposInput[]
  createMany?: Prisma.ticketsCreateManyEquiposInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutEquiposInput | Prisma.ticketsUpdateWithWhereUniqueWithoutEquiposInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutEquiposInput | Prisma.ticketsUpdateManyWithWhereWithoutEquiposInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type ticketsUncheckedUpdateManyWithoutEquiposNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput> | Prisma.ticketsCreateWithoutEquiposInput[] | Prisma.ticketsUncheckedCreateWithoutEquiposInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutEquiposInput | Prisma.ticketsCreateOrConnectWithoutEquiposInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutEquiposInput | Prisma.ticketsUpsertWithWhereUniqueWithoutEquiposInput[]
  createMany?: Prisma.ticketsCreateManyEquiposInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutEquiposInput | Prisma.ticketsUpdateWithWhereUniqueWithoutEquiposInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutEquiposInput | Prisma.ticketsUpdateManyWithWhereWithoutEquiposInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type ticketsCreateNestedOneWithoutMantenimientosInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutMantenimientosInput, Prisma.ticketsUncheckedCreateWithoutMantenimientosInput>
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutMantenimientosInput
  connect?: Prisma.ticketsWhereUniqueInput
}

export type ticketsUpdateOneWithoutMantenimientosNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutMantenimientosInput, Prisma.ticketsUncheckedCreateWithoutMantenimientosInput>
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutMantenimientosInput
  upsert?: Prisma.ticketsUpsertWithoutMantenimientosInput
  disconnect?: Prisma.ticketsWhereInput | boolean
  delete?: Prisma.ticketsWhereInput | boolean
  connect?: Prisma.ticketsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ticketsUpdateToOneWithWhereWithoutMantenimientosInput, Prisma.ticketsUpdateWithoutMantenimientosInput>, Prisma.ticketsUncheckedUpdateWithoutMantenimientosInput>
}

export type ticketsCreateNestedManyWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsCreateNestedManyWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsUncheckedCreateNestedManyWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsUncheckedCreateNestedManyWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInputEnvelope
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
}

export type ticketsUpdateManyWithoutUsuarios_tickets_solicitante_idTousuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type ticketsUpdateManyWithoutUsuarios_tickets_tecnico_idTousuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type ticketsUncheckedUpdateManyWithoutUsuarios_tickets_solicitante_idTousuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_solicitante_idTousuariosInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type ticketsUncheckedUpdateManyWithoutUsuarios_tickets_tecnico_idTousuariosNestedInput = {
  create?: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput> | Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[] | Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  connectOrCreate?: Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  upsert?: Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  createMany?: Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInputEnvelope
  set?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  disconnect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  delete?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  connect?: Prisma.ticketsWhereUniqueInput | Prisma.ticketsWhereUniqueInput[]
  update?: Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  updateMany?: Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsUpdateManyWithWhereWithoutUsuarios_tickets_tecnico_idTousuariosInput[]
  deleteMany?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ticketsCreateWithoutEquiposInput = {
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  usuarios_tickets_solicitante_idTousuarios: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_solicitante_idTousuariosInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_tecnico_idTousuariosInput
  mantenimientos?: Prisma.MantenimientoCreateNestedManyWithoutTicketInput
}

export type ticketsUncheckedCreateWithoutEquiposInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  solicitante_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketsCreateOrConnectWithoutEquiposInput = {
  where: Prisma.ticketsWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput>
}

export type ticketsCreateManyEquiposInputEnvelope = {
  data: Prisma.ticketsCreateManyEquiposInput | Prisma.ticketsCreateManyEquiposInput[]
  skipDuplicates?: boolean
}

export type ticketsUpsertWithWhereUniqueWithoutEquiposInput = {
  where: Prisma.ticketsWhereUniqueInput
  update: Prisma.XOR<Prisma.ticketsUpdateWithoutEquiposInput, Prisma.ticketsUncheckedUpdateWithoutEquiposInput>
  create: Prisma.XOR<Prisma.ticketsCreateWithoutEquiposInput, Prisma.ticketsUncheckedCreateWithoutEquiposInput>
}

export type ticketsUpdateWithWhereUniqueWithoutEquiposInput = {
  where: Prisma.ticketsWhereUniqueInput
  data: Prisma.XOR<Prisma.ticketsUpdateWithoutEquiposInput, Prisma.ticketsUncheckedUpdateWithoutEquiposInput>
}

export type ticketsUpdateManyWithWhereWithoutEquiposInput = {
  where: Prisma.ticketsScalarWhereInput
  data: Prisma.XOR<Prisma.ticketsUpdateManyMutationInput, Prisma.ticketsUncheckedUpdateManyWithoutEquiposInput>
}

export type ticketsScalarWhereInput = {
  AND?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
  OR?: Prisma.ticketsScalarWhereInput[]
  NOT?: Prisma.ticketsScalarWhereInput | Prisma.ticketsScalarWhereInput[]
  id?: Prisma.IntFilter<"tickets"> | number
  titulo?: Prisma.StringFilter<"tickets"> | string
  descripcion?: Prisma.StringFilter<"tickets"> | string
  prioridad?: Prisma.StringFilter<"tickets"> | string
  estado?: Prisma.StringFilter<"tickets"> | string
  equipo_id?: Prisma.IntFilter<"tickets"> | number
  solicitante_id?: Prisma.IntFilter<"tickets"> | number
  tecnico_id?: Prisma.IntNullableFilter<"tickets"> | number | null
  fecha_cierre?: Prisma.DateTimeNullableFilter<"tickets"> | Date | string | null
  creado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
  actualizado_en?: Prisma.DateTimeFilter<"tickets"> | Date | string
}

export type ticketsCreateWithoutMantenimientosInput = {
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  equipos: Prisma.EquipoCreateNestedOneWithoutTicketsInput
  usuarios_tickets_solicitante_idTousuarios: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_solicitante_idTousuariosInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_tecnico_idTousuariosInput
}

export type ticketsUncheckedCreateWithoutMantenimientosInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  solicitante_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
}

export type ticketsCreateOrConnectWithoutMantenimientosInput = {
  where: Prisma.ticketsWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketsCreateWithoutMantenimientosInput, Prisma.ticketsUncheckedCreateWithoutMantenimientosInput>
}

export type ticketsUpsertWithoutMantenimientosInput = {
  update: Prisma.XOR<Prisma.ticketsUpdateWithoutMantenimientosInput, Prisma.ticketsUncheckedUpdateWithoutMantenimientosInput>
  create: Prisma.XOR<Prisma.ticketsCreateWithoutMantenimientosInput, Prisma.ticketsUncheckedCreateWithoutMantenimientosInput>
  where?: Prisma.ticketsWhereInput
}

export type ticketsUpdateToOneWithWhereWithoutMantenimientosInput = {
  where?: Prisma.ticketsWhereInput
  data: Prisma.XOR<Prisma.ticketsUpdateWithoutMantenimientosInput, Prisma.ticketsUncheckedUpdateWithoutMantenimientosInput>
}

export type ticketsUpdateWithoutMantenimientosInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipos?: Prisma.EquipoUpdateOneRequiredWithoutTicketsNestedInput
  usuarios_tickets_solicitante_idTousuarios?: Prisma.UsuarioUpdateOneRequiredWithoutTickets_tickets_solicitante_idTousuariosNestedInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioUpdateOneWithoutTickets_tickets_tecnico_idTousuariosNestedInput
}

export type ticketsUncheckedUpdateWithoutMantenimientosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  equipos: Prisma.EquipoCreateNestedOneWithoutTicketsInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_tecnico_idTousuariosInput
  mantenimientos?: Prisma.MantenimientoCreateNestedManyWithoutTicketInput
}

export type ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketsCreateOrConnectWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput>
}

export type ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInputEnvelope = {
  data: Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInput | Prisma.ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInput[]
  skipDuplicates?: boolean
}

export type ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  equipos: Prisma.EquipoCreateNestedOneWithoutTicketsInput
  usuarios_tickets_solicitante_idTousuarios: Prisma.UsuarioCreateNestedOneWithoutTickets_tickets_solicitante_idTousuariosInput
  mantenimientos?: Prisma.MantenimientoCreateNestedManyWithoutTicketInput
}

export type ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  solicitante_id: number
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketsCreateOrConnectWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput>
}

export type ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInputEnvelope = {
  data: Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInput | Prisma.ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInput[]
  skipDuplicates?: boolean
}

export type ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  update: Prisma.XOR<Prisma.ticketsUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput>
  create: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_solicitante_idTousuariosInput>
}

export type ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  data: Prisma.XOR<Prisma.ticketsUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput, Prisma.ticketsUncheckedUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput>
}

export type ticketsUpdateManyWithWhereWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  where: Prisma.ticketsScalarWhereInput
  data: Prisma.XOR<Prisma.ticketsUpdateManyMutationInput, Prisma.ticketsUncheckedUpdateManyWithoutUsuarios_tickets_solicitante_idTousuariosInput>
}

export type ticketsUpsertWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  update: Prisma.XOR<Prisma.ticketsUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput>
  create: Prisma.XOR<Prisma.ticketsCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedCreateWithoutUsuarios_tickets_tecnico_idTousuariosInput>
}

export type ticketsUpdateWithWhereUniqueWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  where: Prisma.ticketsWhereUniqueInput
  data: Prisma.XOR<Prisma.ticketsUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput, Prisma.ticketsUncheckedUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput>
}

export type ticketsUpdateManyWithWhereWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  where: Prisma.ticketsScalarWhereInput
  data: Prisma.XOR<Prisma.ticketsUpdateManyMutationInput, Prisma.ticketsUncheckedUpdateManyWithoutUsuarios_tickets_tecnico_idTousuariosInput>
}

export type ticketsCreateManyEquiposInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  solicitante_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
}

export type ticketsUpdateWithoutEquiposInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarios_tickets_solicitante_idTousuarios?: Prisma.UsuarioUpdateOneRequiredWithoutTickets_tickets_solicitante_idTousuariosNestedInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioUpdateOneWithoutTickets_tickets_tecnico_idTousuariosNestedInput
  mantenimientos?: Prisma.MantenimientoUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateWithoutEquiposInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateManyWithoutEquiposInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ticketsCreateManyUsuarios_tickets_solicitante_idTousuariosInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  tecnico_id?: number | null
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
}

export type ticketsCreateManyUsuarios_tickets_tecnico_idTousuariosInput = {
  id?: number
  titulo: string
  descripcion: string
  prioridad?: string
  estado?: string
  equipo_id: number
  solicitante_id: number
  fecha_cierre?: Date | string | null
  creado_en?: Date | string
  actualizado_en?: Date | string
}

export type ticketsUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipos?: Prisma.EquipoUpdateOneRequiredWithoutTicketsNestedInput
  usuarios_tickets_tecnico_idTousuarios?: Prisma.UsuarioUpdateOneWithoutTickets_tickets_tecnico_idTousuariosNestedInput
  mantenimientos?: Prisma.MantenimientoUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateManyWithoutUsuarios_tickets_solicitante_idTousuariosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  tecnico_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ticketsUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  equipos?: Prisma.EquipoUpdateOneRequiredWithoutTicketsNestedInput
  usuarios_tickets_solicitante_idTousuarios?: Prisma.UsuarioUpdateOneRequiredWithoutTickets_tickets_solicitante_idTousuariosNestedInput
  mantenimientos?: Prisma.MantenimientoUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mantenimientos?: Prisma.MantenimientoUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketsUncheckedUpdateManyWithoutUsuarios_tickets_tecnico_idTousuariosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  prioridad?: Prisma.StringFieldUpdateOperationsInput | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  equipo_id?: Prisma.IntFieldUpdateOperationsInput | number
  solicitante_id?: Prisma.IntFieldUpdateOperationsInput | number
  fecha_cierre?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  creado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizado_en?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TicketsCountOutputType
 */

export type TicketsCountOutputType = {
  mantenimientos: number
}

export type TicketsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mantenimientos?: boolean | TicketsCountOutputTypeCountMantenimientosArgs
}

/**
 * TicketsCountOutputType without action
 */
export type TicketsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketsCountOutputType
   */
  select?: Prisma.TicketsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TicketsCountOutputType without action
 */
export type TicketsCountOutputTypeCountMantenimientosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MantenimientoWhereInput
}


export type ticketsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  descripcion?: boolean
  prioridad?: boolean
  estado?: boolean
  equipo_id?: boolean
  solicitante_id?: boolean
  tecnico_id?: boolean
  fecha_cierre?: boolean
  creado_en?: boolean
  actualizado_en?: boolean
  equipos?: boolean | Prisma.EquipoDefaultArgs<ExtArgs>
  usuarios_tickets_solicitante_idTousuarios?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  usuarios_tickets_tecnico_idTousuarios?: boolean | Prisma.tickets$usuarios_tickets_tecnico_idTousuariosArgs<ExtArgs>
  mantenimientos?: boolean | Prisma.tickets$mantenimientosArgs<ExtArgs>
  _count?: boolean | Prisma.TicketsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tickets"]>



export type ticketsSelectScalar = {
  id?: boolean
  titulo?: boolean
  descripcion?: boolean
  prioridad?: boolean
  estado?: boolean
  equipo_id?: boolean
  solicitante_id?: boolean
  tecnico_id?: boolean
  fecha_cierre?: boolean
  creado_en?: boolean
  actualizado_en?: boolean
}

export type ticketsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "titulo" | "descripcion" | "prioridad" | "estado" | "equipo_id" | "solicitante_id" | "tecnico_id" | "fecha_cierre" | "creado_en" | "actualizado_en", ExtArgs["result"]["tickets"]>
export type ticketsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  equipos?: boolean | Prisma.EquipoDefaultArgs<ExtArgs>
  usuarios_tickets_solicitante_idTousuarios?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  usuarios_tickets_tecnico_idTousuarios?: boolean | Prisma.tickets$usuarios_tickets_tecnico_idTousuariosArgs<ExtArgs>
  mantenimientos?: boolean | Prisma.tickets$mantenimientosArgs<ExtArgs>
  _count?: boolean | Prisma.TicketsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ticketsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tickets"
  objects: {
    equipos: Prisma.$EquipoPayload<ExtArgs>
    usuarios_tickets_solicitante_idTousuarios: Prisma.$UsuarioPayload<ExtArgs>
    usuarios_tickets_tecnico_idTousuarios: Prisma.$UsuarioPayload<ExtArgs> | null
    mantenimientos: Prisma.$MantenimientoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    titulo: string
    descripcion: string
    prioridad: string
    estado: string
    equipo_id: number
    solicitante_id: number
    tecnico_id: number | null
    fecha_cierre: Date | null
    creado_en: Date
    actualizado_en: Date
  }, ExtArgs["result"]["tickets"]>
  composites: {}
}

export type ticketsGetPayload<S extends boolean | null | undefined | ticketsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ticketsPayload, S>

export type ticketsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ticketsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketsCountAggregateInputType | true
  }

export interface ticketsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tickets'], meta: { name: 'tickets' } }
  /**
   * Find zero or one Tickets that matches the filter.
   * @param {ticketsFindUniqueArgs} args - Arguments to find a Tickets
   * @example
   * // Get one Tickets
   * const tickets = await prisma.tickets.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ticketsFindUniqueArgs>(args: Prisma.SelectSubset<T, ticketsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tickets that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ticketsFindUniqueOrThrowArgs} args - Arguments to find a Tickets
   * @example
   * // Get one Tickets
   * const tickets = await prisma.tickets.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ticketsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ticketsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsFindFirstArgs} args - Arguments to find a Tickets
   * @example
   * // Get one Tickets
   * const tickets = await prisma.tickets.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ticketsFindFirstArgs>(args?: Prisma.SelectSubset<T, ticketsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tickets that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsFindFirstOrThrowArgs} args - Arguments to find a Tickets
   * @example
   * // Get one Tickets
   * const tickets = await prisma.tickets.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ticketsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ticketsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tickets
   * const tickets = await prisma.tickets.findMany()
   * 
   * // Get first 10 Tickets
   * const tickets = await prisma.tickets.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketsWithIdOnly = await prisma.tickets.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ticketsFindManyArgs>(args?: Prisma.SelectSubset<T, ticketsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tickets.
   * @param {ticketsCreateArgs} args - Arguments to create a Tickets.
   * @example
   * // Create one Tickets
   * const Tickets = await prisma.tickets.create({
   *   data: {
   *     // ... data to create a Tickets
   *   }
   * })
   * 
   */
  create<T extends ticketsCreateArgs>(args: Prisma.SelectSubset<T, ticketsCreateArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tickets.
   * @param {ticketsCreateManyArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const tickets = await prisma.tickets.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ticketsCreateManyArgs>(args?: Prisma.SelectSubset<T, ticketsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Tickets.
   * @param {ticketsDeleteArgs} args - Arguments to delete one Tickets.
   * @example
   * // Delete one Tickets
   * const Tickets = await prisma.tickets.delete({
   *   where: {
   *     // ... filter to delete one Tickets
   *   }
   * })
   * 
   */
  delete<T extends ticketsDeleteArgs>(args: Prisma.SelectSubset<T, ticketsDeleteArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tickets.
   * @param {ticketsUpdateArgs} args - Arguments to update one Tickets.
   * @example
   * // Update one Tickets
   * const tickets = await prisma.tickets.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ticketsUpdateArgs>(args: Prisma.SelectSubset<T, ticketsUpdateArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tickets.
   * @param {ticketsDeleteManyArgs} args - Arguments to filter Tickets to delete.
   * @example
   * // Delete a few Tickets
   * const { count } = await prisma.tickets.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ticketsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ticketsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tickets
   * const tickets = await prisma.tickets.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ticketsUpdateManyArgs>(args: Prisma.SelectSubset<T, ticketsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Tickets.
   * @param {ticketsUpsertArgs} args - Arguments to update or create a Tickets.
   * @example
   * // Update or create a Tickets
   * const tickets = await prisma.tickets.upsert({
   *   create: {
   *     // ... data to create a Tickets
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tickets we want to update
   *   }
   * })
   */
  upsert<T extends ticketsUpsertArgs>(args: Prisma.SelectSubset<T, ticketsUpsertArgs<ExtArgs>>): Prisma.Prisma__ticketsClient<runtime.Types.Result.GetResult<Prisma.$ticketsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsCountArgs} args - Arguments to filter Tickets to count.
   * @example
   * // Count the number of Tickets
   * const count = await prisma.tickets.count({
   *   where: {
   *     // ... the filter for the Tickets we want to count
   *   }
   * })
  **/
  count<T extends ticketsCountArgs>(
    args?: Prisma.Subset<T, ticketsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketsAggregateArgs>(args: Prisma.Subset<T, TicketsAggregateArgs>): Prisma.PrismaPromise<GetTicketsAggregateType<T>>

  /**
   * Group by Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ticketsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ticketsGroupByArgs['orderBy'] }
      : { orderBy?: ticketsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ticketsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tickets model
 */
readonly fields: ticketsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tickets.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ticketsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  equipos<T extends Prisma.EquipoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EquipoDefaultArgs<ExtArgs>>): Prisma.Prisma__EquipoClient<runtime.Types.Result.GetResult<Prisma.$EquipoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  usuarios_tickets_solicitante_idTousuarios<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  usuarios_tickets_tecnico_idTousuarios<T extends Prisma.tickets$usuarios_tickets_tecnico_idTousuariosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tickets$usuarios_tickets_tecnico_idTousuariosArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  mantenimientos<T extends Prisma.tickets$mantenimientosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tickets$mantenimientosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MantenimientoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tickets model
 */
export interface ticketsFieldRefs {
  readonly id: Prisma.FieldRef<"tickets", 'Int'>
  readonly titulo: Prisma.FieldRef<"tickets", 'String'>
  readonly descripcion: Prisma.FieldRef<"tickets", 'String'>
  readonly prioridad: Prisma.FieldRef<"tickets", 'String'>
  readonly estado: Prisma.FieldRef<"tickets", 'String'>
  readonly equipo_id: Prisma.FieldRef<"tickets", 'Int'>
  readonly solicitante_id: Prisma.FieldRef<"tickets", 'Int'>
  readonly tecnico_id: Prisma.FieldRef<"tickets", 'Int'>
  readonly fecha_cierre: Prisma.FieldRef<"tickets", 'DateTime'>
  readonly creado_en: Prisma.FieldRef<"tickets", 'DateTime'>
  readonly actualizado_en: Prisma.FieldRef<"tickets", 'DateTime'>
}
    

// Custom InputTypes
/**
 * tickets findUnique
 */
export type ticketsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where: Prisma.ticketsWhereUniqueInput
}

/**
 * tickets findUniqueOrThrow
 */
export type ticketsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where: Prisma.ticketsWhereUniqueInput
}

/**
 * tickets findFirst
 */
export type ticketsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where?: Prisma.ticketsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketsOrderByWithRelationInput | Prisma.ticketsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tickets.
   */
  cursor?: Prisma.ticketsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tickets.
   */
  distinct?: Prisma.TicketsScalarFieldEnum | Prisma.TicketsScalarFieldEnum[]
}

/**
 * tickets findFirstOrThrow
 */
export type ticketsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where?: Prisma.ticketsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketsOrderByWithRelationInput | Prisma.ticketsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tickets.
   */
  cursor?: Prisma.ticketsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tickets.
   */
  distinct?: Prisma.TicketsScalarFieldEnum | Prisma.TicketsScalarFieldEnum[]
}

/**
 * tickets findMany
 */
export type ticketsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where?: Prisma.ticketsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketsOrderByWithRelationInput | Prisma.ticketsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tickets.
   */
  cursor?: Prisma.ticketsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tickets.
   */
  distinct?: Prisma.TicketsScalarFieldEnum | Prisma.TicketsScalarFieldEnum[]
}

/**
 * tickets create
 */
export type ticketsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * The data needed to create a tickets.
   */
  data: Prisma.XOR<Prisma.ticketsCreateInput, Prisma.ticketsUncheckedCreateInput>
}

/**
 * tickets createMany
 */
export type ticketsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tickets.
   */
  data: Prisma.ticketsCreateManyInput | Prisma.ticketsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tickets update
 */
export type ticketsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * The data needed to update a tickets.
   */
  data: Prisma.XOR<Prisma.ticketsUpdateInput, Prisma.ticketsUncheckedUpdateInput>
  /**
   * Choose, which tickets to update.
   */
  where: Prisma.ticketsWhereUniqueInput
}

/**
 * tickets updateMany
 */
export type ticketsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tickets.
   */
  data: Prisma.XOR<Prisma.ticketsUpdateManyMutationInput, Prisma.ticketsUncheckedUpdateManyInput>
  /**
   * Filter which tickets to update
   */
  where?: Prisma.ticketsWhereInput
  /**
   * Limit how many tickets to update.
   */
  limit?: number
}

/**
 * tickets upsert
 */
export type ticketsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * The filter to search for the tickets to update in case it exists.
   */
  where: Prisma.ticketsWhereUniqueInput
  /**
   * In case the tickets found by the `where` argument doesn't exist, create a new tickets with this data.
   */
  create: Prisma.XOR<Prisma.ticketsCreateInput, Prisma.ticketsUncheckedCreateInput>
  /**
   * In case the tickets was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ticketsUpdateInput, Prisma.ticketsUncheckedUpdateInput>
}

/**
 * tickets delete
 */
export type ticketsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
  /**
   * Filter which tickets to delete.
   */
  where: Prisma.ticketsWhereUniqueInput
}

/**
 * tickets deleteMany
 */
export type ticketsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tickets to delete
   */
  where?: Prisma.ticketsWhereInput
  /**
   * Limit how many tickets to delete.
   */
  limit?: number
}

/**
 * tickets.usuarios_tickets_tecnico_idTousuarios
 */
export type tickets$usuarios_tickets_tecnico_idTousuariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuario
   */
  select?: Prisma.UsuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuario
   */
  omit?: Prisma.UsuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuarioInclude<ExtArgs> | null
  where?: Prisma.UsuarioWhereInput
}

/**
 * tickets.mantenimientos
 */
export type tickets$mantenimientosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mantenimiento
   */
  select?: Prisma.MantenimientoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mantenimiento
   */
  omit?: Prisma.MantenimientoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MantenimientoInclude<ExtArgs> | null
  where?: Prisma.MantenimientoWhereInput
  orderBy?: Prisma.MantenimientoOrderByWithRelationInput | Prisma.MantenimientoOrderByWithRelationInput[]
  cursor?: Prisma.MantenimientoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MantenimientoScalarFieldEnum | Prisma.MantenimientoScalarFieldEnum[]
}

/**
 * tickets without action
 */
export type ticketsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tickets
   */
  select?: Prisma.ticketsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tickets
   */
  omit?: Prisma.ticketsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketsInclude<ExtArgs> | null
}
