
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const usuarios_rol = {
  SOLICITANTE: 'SOLICITANTE',
  TECNICO: 'TECNICO',
  ADMINISTRADOR: 'ADMINISTRADOR',
  SUPERVISOR: 'SUPERVISOR'
} as const

export type usuarios_rol = (typeof usuarios_rol)[keyof typeof usuarios_rol]
