
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Equipo'
export type * from './models/Mantenimiento'
export type * from './models/Usuario'
export type * from './models/tickets'
export type * from './models/Repuesto'
export type * from './models/RepuestoMantenimiento'
export type * from './commonInputTypes'